---
# More schema_registry variables are defined in the confluent.variables role

### Boolean to enable cp-ansible's Custom Log4j Configuration
schema_registry_custom_log4j: "{{ custom_log4j }}"

schema_registry_java_args:
  - "{% if schema_registry_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if schema_registry_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=port={{schema_registry_jolokia_port}},host=0.0.0.0{% if schema_registry_jolokia_ssl_enabled|bool %},keystore={{schema_registry_keystore_path}},keystorePassword={{schema_registry_keystore_storepass}},protocol=https{% endif %}{% endif %}"
  - "{% if schema_registry_custom_log4j|bool %}-Dlog4j.configuration=file:{{schema_registry.log4j_file}}{% endif %}"
  - "{% if schema_registry_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{schema_registry_jmxexporter_port}}:{{schema_registry_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the Schema Registry Process
schema_registry_custom_java_args: ""

schema_registry_final_java_args: "{{ schema_registry_java_args + [ schema_registry_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
schema_registry_service_overrides:
  LimitNOFILE: 100000
  User: "{{ schema_registry_user if schema_registry_user != schema_registry_default_user else '' }}"
  Group: "{{ schema_registry_group if schema_registry_group != schema_registry_default_group else '' }}"
schema_registry_service_environment_overrides:
  SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  SCHEMA_REGISTRY_OPTS: "{{ schema_registry_final_java_args | java_arg_build_out }}"

schema_registry:
  appender_log_path: /var/log/confluent/schema-registry/
  appender_log_name: schema-registry.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
