schema_registry_listener_port: 8081

schema_registry_open_file_limit: "{{open_file_limit}}"

schema_registry_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{schema_registry_jolokia_port}},host=0.0.0.0"
schema_registry_jolokia_java_arg: "{{ schema_registry_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

schema_registry_service_overrides:
  LimitNOFILE: "{{schema_registry_open_file_limit}}"
schema_registry_service_environment_overrides:
  SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  SCHEMA_REGISTRY_OPTS: "{{schema_registry_jolokia_java_arg}}"

schema_registry_packages:
  - confluent-schema-registry
  - confluent-security

schema_registry:
  user: cp-schema-registry
  group: confluent
  config_file: /etc/schema-registry/schema-registry.properties
  service_name: confluent-schema-registry
  systemd_file: /usr/lib/systemd/system/confluent-schema-registry.service
  systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
  properties:
    listeners: http://0.0.0.0:{{schema_registry_listener_port}}
    debug: false
    kafkastore.topic: _schemas
    kafkastore.ssl.endpoint.identification.algorithm: ""
  systemd:
    enabled: yes
    state: started
