---
- name: Copy CA Cert to Host
  copy:
    src: "{{ssl_ca_cert_filepath}}"
    dest: "/var/ssl/private/ldaps/{{ssl_ca_cert_filepath|basename}}"
    mode: 0666

- name: Copy Signed Cert to Host
  copy:
    src: "{{ssl_signed_cert_filepath}}"
    dest: "/var/ssl/private/ldaps/{{ssl_signed_cert_filepath|basename}}"
    mode: 0666

- name: Copy Key to Host
  copy:
    src: "{{ssl_key_filepath}}"
    dest: "/var/ssl/private/ldaps/{{ssl_key_filepath|basename}}"
    mode: 0666
