---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
- pattern: 'kafka.schema.registry<type=jetty-metrics>([^:]+):'
  name: "schema_registry_jetty_metrics_$1"
- pattern: 'kafka.schema.registry<type=master-slave-role>([^:]+):'
  name: "schema_registry_master_slave_role"
- pattern: 'kafka.schema.registry<type=jersey-metrics>([^:]+):'
  name: "schema_registry_jersey_metrics_$1"
