- name: connect distributed create group
  group:
    name: "{{kafka.connect.distributed.group}}"
- name: connect distributed create user
  user:
    name: "{{kafka.connect.distributed.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{kafka.connect.distributed.group}}"
- name: connect distributed create config
  template:
    src: connect-distributed.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
  notify:
    - restart connect distributed
- name: create systemd override file
  file:
    path: "{{kafka.connect.distributed.systemd_override}}"
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
    state: directory
    mode: 0640
- name: write environment variables
  template:
    src: environment.j2
    dest: "{{kafka.connect.distributed.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
  notify:
    - reload systemd
    - restart connect distributed
- name: connect distributed configure service
  systemd:
    name: "{{kafka.connect.distributed.service_name}}"
    enabled: "{{kafka.connect.distributed.systemd.enabled}}"
    state: "{{kafka.connect.distributed.systemd.state}}"    
