- name: connect distributed create group
  group:
    name: "{{kafka.connect.distributed.group}}"
- name: connect distributed create user
  user:
    name: "{{kafka.connect.distributed.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{kafka.connect.distributed.group}}"
- name: connect distributed create config
  template:
    src: connect-distributed.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart connect distributed
- name: connect distributed create config
  template:
    src: connect-distributed_ssl.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
  when: security_mode == "ssl"
  notify:
    - restart connect distributed
- name: connect distributed create config
  template:
    src: connect-distributed_sasl_ssl.properties.j2
    dest: "{{kafka.connect.distributed.config_file}}"
    mode: 0640
    owner: "{{kafka.connect.distributed.user}}"
    group: "{{kafka.connect.distributed.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart connect distributed
- name: connect distributed configure service
  systemd:
    name: "{{kafka.connect.distributed.service_name}}"
    enabled: "{{kafka.connect.distributed.systemd.enabled}}"
    state: "{{kafka.connect.distributed.systemd.state}}"    
