zookeeper_service_name: confluent-zookeeper
zookeeper_main_package: "{{ 'confluent-server' if confluent_server_enabled|bool else 'confluent-kafka-2.12'}}"
zookeeper_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ zookeeper_main_package }}"
zookeeper_default_user: cp-kafka
zookeeper_default_group: confluent
zookeeper:
  config_file: /etc/kafka/zookeeper.properties
  systemd_file: /usr/lib/systemd/system/{{zookeeper_service_name}}.service
  systemd_override: /etc/systemd/system/{{zookeeper_service_name}}.service.d/override.conf

kafka_broker_service_name: "{{ 'confluent-server' if confluent_server_enabled|bool else 'confluent-kafka'}}"
kafka_broker_main_package: "{{ 'confluent-server' if confluent_server_enabled|bool else 'confluent-kafka-2.12'}}"
kafka_broker_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-rebalancer
  - confluent-security
kafka_broker_default_user: cp-kafka
kafka_broker_default_group: confluent
kafka_broker:
  config_file: /etc/kafka/server.properties
  systemd_file: /usr/lib/systemd/system/{{kafka_broker_service_name}}.service
  systemd_override: /etc/systemd/system/{{kafka_broker_service_name}}.service.d/override.conf

schema_registry_service_name: confluent-schema-registry
schema_registry_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-schema-registry
  - confluent-security
schema_registry_default_user: cp-schema-registry
schema_registry_default_group: confluent
schema_registry:
  config_file: /etc/schema-registry/schema-registry.properties
  systemd_file: /usr/lib/systemd/system/{{schema_registry_service_name}}.service
  systemd_override: /etc/systemd/system/{{schema_registry_service_name}}.service.d/override.conf

kafka_connect_service_name: confluent-kafka-connect
kafka_connect_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-kafka-connect-storage-common
  - confluent-kafka-connect-s3
  - confluent-kafka-connect-elasticsearch
  - confluent-kafka-connect-jdbc
  - confluent-kafka-connect-jms
  - confluent-kafka-connect-replicator
  - confluent-security
  - confluent-control-center-fe
  - confluent-control-center
  - confluent-schema-registry
kafka_connect_default_user: cp-kafka-connect
kafka_connect_default_group: confluent
kafka_connect:
  config_file: /etc/kafka/connect-distributed.properties
  systemd_file: /usr/lib/systemd/system/{{kafka_connect_service_name}}.service
  systemd_override: /etc/systemd/system/{{kafka_connect_service_name}}.service.d/override.conf

ksql_service_name: confluent-ksql
ksql_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-ksql
  - confluent-security
ksql_default_user: cp-ksql
ksql_default_group: confluent
ksql:
  config_file: /etc/ksql/ksql-server.properties
  systemd_file: /usr/lib/systemd/system/{{ksql_service_name}}.service
  systemd_override: /etc/systemd/system/{{ksql_service_name}}.service.d/override.conf

kafka_rest_service_name: confluent-kafka-rest
kafka_rest_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-kafka-rest
  - confluent-security
kafka_rest_default_user: cp-kafka-rest
kafka_rest_default_group: confluent
kafka_rest:
  config_file: /etc/kafka-rest/kafka-rest.properties
  systemd_file: /usr/lib/systemd/system/{{kafka_rest_service_name}}.service
  systemd_override: /etc/systemd/system/{{kafka_rest_service_name}}.service.d/override.conf

control_center_service_name: confluent-control-center
control_center_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-control-center-fe
  - confluent-control-center
control_center_default_user: cp-control-center
control_center_default_group: confluent
control_center:
  config_file: /etc/confluent-control-center/control-center-production.properties
  systemd_file: /usr/lib/systemd/system/{{control_center_service_name}}.service
  systemd_override: /etc/systemd/system/{{control_center_service_name}}.service.d/override.conf
