---
- name: Verify - kafka_broker
  hosts: kafka_broker2
  gather_facts: false
  tasks:
    - name: Check 2 way tls line omitted in properties
      shell: |
        grep "confluent.metadata.server.ssl.truststore.location"  /etc/kafka/server.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 1

    - name: Get Kafka Cluster ID from Embedded Rest Proxy
      uri:
        url: "http://{{ inventory_hostname }}:8090/kafka/v3/clusters"
        method: GET
        validate_certs: false
        body_format: json
        return_content: true
        status_code: 200
        url_username: mds
        url_password: password
        force_basic_auth: true
      register: cluster_id_query

    - name: Parse Kafka Cluster ID from json query
      set_fact:
        kafka_cluster_id: "{{ cluster_id_query.json.data[0].cluster_id }}"

    - name: Get Topics as Regular LDAP User
      uri:
        url: "http://{{ inventory_hostname }}:8090/kafka/v3/clusters/{{kafka_cluster_id}}/topics"
        method: GET
        validate_certs: false
        body_format: json
        return_content: true
        status_code: 200
        url_username: kafka_broker
        url_password: password
        force_basic_auth: true
      register: topics_request

    - name: Assert property set as expected
      assert:
        that:
          - topics_request.json.data | length == 0
        fail_msg: "Regular user should not be able to see any topics"
        quiet: true

    - name: Get Topics as MDS Super User
      uri:
        url: "http://{{ inventory_hostname }}:8090/kafka/v3/clusters/{{kafka_cluster_id}}/topics"
        method: GET
        validate_certs: false
        body_format: json
        return_content: true
        status_code: 200
        url_username: mds
        url_password: password
        force_basic_auth: true
      register: topics_request

    - name: Assert property set as expected
      assert:
        that:
          - topics_request.json.data | length > 0
        fail_msg: "MDS Super User should be able to view many topics"
        quiet: true

- name: Verify - schema_registry
  hosts: schema_registry2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_rest
  hosts: kafka_rest2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_connect
  hosts: kafka_connect2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - ksql
  hosts: ksql2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090


- name: Verify - control_center
  hosts: control_center2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090
