---
- name: Gather OS Facts
  setup:
    filter: ansible_os_family

- name: Load server.properties
  slurp:
    src: "{{ kafka_broker.config_file }}"
  register: slurped_properties

- name: Load meta.properties
  slurp:
    src: "{{ kafka_broker_final_properties['log.dirs'].split(',')[0] }}/meta.properties"
  register: slurped_meta_properties

# Zookeeper shell cannot read server.properties if secrets protection is enabled. Creates a non encrypted file
- name: Create Zookeeper TLS Client Config
  template:
    src: zookeeper-tls-client.properties.j2
    dest: "{{ kafka_broker.zookeeper_tls_client_config_file }}"
    mode: 0640
    owner: "{{ kafka_broker_user }}"
    group: "{{ kafka_broker_group }}"
  when: zookeeper_ssl_enabled|bool
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Load override.conf - Archive Installer
  slurp:
    src: "{{ kafka_broker.systemd_override }}"
  register: slurped_override
  when: installation_method == "archive"
  tags:
    - systemd
- name: Set kafka_broker_current_version variable - Archive Installer
  set_fact:
    kafka_broker_current_version: "{{ (slurped_override.content|b64decode) .split('\n') |
      select('match', '^ExecStart=' + archive_config_base_path + '/confluent-(.*)/bin/kafka-server-start ' + kafka_broker.config_file) |
      list | first | regex_search('confluent-([0-9]+(.[0-9]+)+)/bin/', '\\1') | first }}"
  when: installation_method == "archive"
  tags:
    - systemd
# TODO When Zookeeper is removed, use kafka-metadata-quorum script. See KIP-595
- name: Get Controller Broker ID
  shell: >
    set -o pipefail &&
      {{ binary_base_path }}/bin/zookeeper-shell {{ hostvars[groups['zookeeper'][0]] | confluent.platform.resolve_hostname }}:{{ zookeeper_client_port }}{{zookeeper_chroot}}
          {%- if zookeeper_ssl_enabled %}
            -zk-tls-config-file {{ kafka_broker.zookeeper_tls_client_config_file }}
          {%- endif %}
          get /controller | grep brokerid
  args:
    executable: /bin/bash
  vars:
    archive_version: "{{ kafka_broker_current_version | default(confluent_package_version) }}"
  register: controller_query
  run_once: true
  changed_when: false
  check_mode: false
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Get broker_id
  set_fact:
    controller_json: "{{ controller_query.stdout }}"
    broker_id: "{{ (slurped_meta_properties.content|b64decode).split('\n') | select('match', '^broker.id.*') | list \
      | first | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1') }}"

- debug:
    msg: "Broker ID: {{ broker_id }} and Controller ID: {{ controller_json.brokerid }}"

- name: "Group Hosts by Kafka Broker Mode: Non Controller or Controller"
  group_by:
    key: "{{ 'kafka_broker_controller' if broker_id|int == controller_json.brokerid|int else 'kafka_broker_non_controller' }}"
  changed_when: false
