---
- name: extract uuid from meta.properties
  slurp:
    src: "{{ kafka_controller_final_properties['log.dirs'] }}/meta.properties"
  delegate_to: "{{ groups.kafka_controller[0] }}"
  register: uuid_broker

- set_fact:
    uuid_key_broker: "{{ uuid_broker['content'] | b64decode}} "

- name: get CLUSTER_ID
  set_fact:
    clusterid: "{{ uuid_key_broker.partition('cluster.id=')[2].partition('\n')[0] }}"

- name: format meta directory
  shell: "{{ binary_base_path }}/bin/kafka-storage  format -t {{ clusterid }} -c {{ kafka_broker.config_file }} --ignore-formatted"
  register: format_meta
