---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_broker_service_name}}"
    state: restarted
  tags:
    - systemd

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_broker_health_check_delay }}"
