---
- name: Set Principal - Sasl Scram
  set_fact:
    kafka_broker_principal: "User:{{ sasl_scram_users_final.admin.principal }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | confluent.platform.normalize_sasl_protocol == 'SCRAM-SHA-512'

- name: Set Principal - Sasl Scram 256
  set_fact:
    kafka_broker_principal: "User:{{ sasl_scram256_users_final.admin.principal }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | confluent.platform.normalize_sasl_protocol == 'SCRAM-SHA-256'

- name: Set Principal - Sasl Plain
  set_fact:
    kafka_broker_principal: "User:{{ sasl_plain_users_final.admin.principal }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | confluent.platform.normalize_sasl_protocol == 'PLAIN'

- name: Set Principal - Sasl Kerberos
  set_fact:
    kafka_broker_principal: "User:{{ kerberos_kafka_broker_primary }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | confluent.platform.normalize_sasl_protocol == 'GSSAPI'

- name: Extract Common Name from Keystore - SSL Mutual Auth
  # Examine the keystore
  # Search lines with Entry type: "PrivateKeyEntry" and return that line and all after, ca cert is of type "trustedCertEntry"
  # Search for first "Owner" line
  # Extract DNAME from line
  # Remove spaces after commas
  shell: |
    keytool -list -keystore {{kafka_broker_keystore_path}} \
        -storepass {{kafka_broker_keystore_storepass}} -v \
        | grep PrivateKeyEntry -A1000 \
        | grep Owner -m1 \
        | cut -d ":" -f2 \
        | cut -c2- \
        | sed 's/\s*,\s*/,/g'
  register: distinguished_name_from_keystore
  changed_when: false
  when:
    - listener['sasl_protocol'] | default(sasl_protocol) | confluent.platform.normalize_sasl_protocol == 'none'
    - listener['ssl_enabled'] | default(ssl_enabled) | bool
    - listener['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool
  no_log: "{{ mask_sensitive_logs|bool }}"

- name: Set Principal - SSL Mutual Auth
  set_fact:
    kafka_broker_principal: "User:{{ distinguished_name_from_keystore.stdout }}"
  when:
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'none'
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool
