---
- name: Verify - kafka_broker
  hosts: kafka_broker2
  gather_facts: false
  tasks:
    - name: Check 2 way tls line omitted in properties
      shell: |
        grep "confluent.metadata.server.ssl.truststore.location"  /etc/kafka/server.properties
      register: linecheck
      check_mode: false
      changed_when: false
      failed_when: linecheck.rc != 1

    - name: Create Topic
      shell: |
        kafka-topics --bootstrap-server mds-kafka-broker1:9091 \
          --command-config /etc/kafka/client.properties \
          --create --if-not-exists --topic test1
      run_once: true

    - name: Consume audit logs topic
      shell: |
        timeout 10 kafka-console-consumer --bootstrap-server kafka-broker1:9091 \
            --consumer.config /etc/kafka/client.properties \
            --from-beginning --topic confluent-audit-log-events
      register: output
      run_once: true
      failed_when: false

    - name: Assert audit log there
      assert:
        that:
          - "'\"resourceType\":\"Topic\",\"resourceName\":\"test1\"' in output.stdout"
        fail_msg: "test1 topic creation should be in audit logs topic"
        quiet: true

- name: Verify - schema_registry
  hosts: schema_registry2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_rest
  hosts: kafka_rest2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - kafka_connect
  hosts: kafka_connect2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090

- name: Verify - ksql
  hosts: ksql2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090


- name: Verify - control_center
  hosts: control_center2
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.metadata.bootstrap.server.urls
        expected_value: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090
