---
galaxy_info:
  author: Confluent
  description: This is common role for installation of prerequite packages and basic directory setup
  company: Confluent
  license: Apache-2.0
  min_ansible_version: '2.16.0'
dependencies:
  - role: variables
