---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-rest1
    hostname: kafka-rest1.confluent
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  inventory:
    group_vars:
      all:
        scenario_name: ccloud-kafka-rest

        sasl_protocol: plain

        kafka_rest_ssl_enabled: true

        kafka_rest_custom_properties:
          bootstrap.servers: kafka-broker1:9092
          client.sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka_rest\" password=\"kafka_rest-secret\";'
          # CClould uses trusted CAs, so typically will be SASL_SSL, this test uses SASL_PLAINTEXT
          # client.security.protocol: SASL_SSL
          client.security.protocol: SASL_PLAINTEXT
          client.sasl.mechanism: PLAIN
          client.ssl.endpoint.identification.algorithm: https
          # CCloud also has SR, this test will not, these properties are for reference
          # schema.registry.basic.auth.credentials.source: USER_INFO
          # schema.registry.basic.auth.user.info: <ommitted>:<ommitted>
          # schema.registry.url: https://<ommitted>
          consumer.retry.backoff.ms: 600
          consumer.request.timeout.ms: 25000
          producer.acks: 1
          admin.request.timeout.ms: 50000

verifier:
  name: ansible
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
