zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
confluent:
  package_name: confluent-platform-2.12
  support:
    customer_id: anonymous
    metrics_enabled: true
  repository:
    debian:
      key_url: https://packages.confluent.io/deb/5.2/archive.key
      repository: "deb [arch=amd64] https://packages.confluent.io/deb/5.2 stable main"
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/5.2
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/5.2/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/5.2/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/5.2/archive.key
        enabled: 1
