---
# Deprecated vars
custom_apt_repo: false
custom_yum_repofile: false

### Configures package repositories on hosts. By default will configure confluent's deb/yum repositories. Possible options: none, confluent, custom. Must also set custom_yum_repofile_filepath or custom_apt_repo_filepath if using custom. Note: vars custom_apt_repo and custom_yum_repofile are deprecated
repository_configuration: "{{'custom' if custom_apt_repo|bool or custom_yum_repofile else 'confluent'}}"

### Full path on control node to custom yum repo file, must also set repository_configuration to custom
custom_yum_repofile_filepath: ""

### Full path on control node to custom apt repo file, must also set repository_configuration to custom
custom_apt_repo_filepath: ""

### Base URL for Confluent's RPM and Debian Package Repositories
confluent_common_repository_baseurl: "https://staging-confluent-packages.s3.us-west-2.amazonaws.com"

confluent_common_repository_debian_baseurl: "{{confluent_common_repository_baseurl}}/deb"
confluent_common_repository_debian_key_url: "{{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_debian_repository: "deb [arch=amd64] {{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}} stable main"

confluent_common_repository_redhat_baseurl: "{{confluent_common_repository_baseurl}}/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1

confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/$releasever"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 1

### Boolean to have cp-ansible install Java on hosts
install_java: true

### Java Package to install on RHEL/Centos hosts. Possible values java-1.8.0-openjdk or java-11-openjdk
redhat_java_package_name: java-1.8.0-openjdk

### Java Package to install on Debian hosts. Possible values openjdk-8-jdk or openjdk-11-jdk
debian_java_package_name: openjdk-8-jdk

### Java Package to install on Ubuntu hosts. Possible values openjdk-8-jdk or openjdk-11-jdk
ubuntu_java_package_name: openjdk-8-jdk

### Deb Repository to use for Java Installation
ubuntu_java_repository: ppa:openjdk-r/ppa

### Version of Jolokia Agent Jar to Download
jolokia_version: 1.6.2

### Full URL used for Jolokia Agent Jar Download. When `jolokia_url_remote=false` this represents the path on Ansible control host.
jolokia_jar_url: "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{{jolokia_version}}/jolokia-jvm-{{jolokia_version}}-agent.jar"

### Version of JmxExporter Agent Jar to Donwload
jmxexporter_version: 0.12.0

### Full URL used for Prometheus Exporter Jar Download. When `jolokia_url_remote=false` this represents the path on Ansible control host.
jmxexporter_jar_url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{jmxexporter_version}}/jmx_prometheus_javaagent-{{jmxexporter_version}}.jar"

### A path reference to a local archive file or URL. By default this is the URL from Confluent's repositories. In an ansible-pull deployment this could be set to a local file such as "~/.ansible/pull/{{inventory_hostname}}/{{confluent_archive_file_name}}".
confluent_archive_file_source: "{{confluent_common_repository_baseurl}}/archive/{{confluent_repo_version}}/confluent{{'' if confluent_server_enabled else '-community'}}-{{confluent_package_version}}.tar.gz"

### Set to true to indicate the archive file is remote (i.e. already on the target node) or a URL. Set to false if the archive file is on the control node.
confluent_archive_file_remote: true

### Base URL for Confluent CLI packages
confluent_cli_repository_baseurl: "https://s3-us-west-2.amazonaws.com/confluent.cloud"

### A path reference to a local archive file or URL. By default this is the URL from Confluent CLI repository.
confluent_cli_archive_file_source: "{{confluent_cli_repository_baseurl}}/confluent-cli/archives/{{confluent_cli_version}}/{{confluent_cli_binary}}_{{(confluent_cli_version == 'latest') | ternary('', 'v')}}{{confluent_cli_version}}_{{ansible_system|lower}}_{{confluent_cli_goarch[ansible_architecture]}}.tar.gz"

### Set to true to indicate the CLI archive file is remote (i.e. already on the target node) or a URL. Set to false if the archive file is on the control node.
confluent_cli_archive_file_remote: true
