confluent_common_repository_baseurl: "https://packages.confluent.io"

confluent_common_repository_debian_baseurl: "{{confluent_common_repository_baseurl}}/deb"
confluent_common_repository_debian_key_url: "{{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_debian_repository: "deb [arch=amd64] {{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}} stable main"

confluent_common_repository_redhat_baseurl: "{{confluent_common_repository_baseurl}}/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1

confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/7"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 1

install_java: true
redhat_java_package_name: java-1.8.0-openjdk
debian_java_package_name: openjdk-8-jdk
ubuntu_java_package_name: openjdk-8-jdk
ubuntu_java_repository: ppa:openjdk-r/ppa

jolokia_version: 1.6.2
jolokia_jar_url: "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{{jolokia_version}}/jolokia-jvm-{{jolokia_version}}-agent.jar"

jmxexporter_jar_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar
