---
- name: Creating Confluent Hub Install Dir
  file:
    path: "{{kafka_connect_confluent_hub_client.install_dir}}"
    state: directory
    group: "{{kafka_connect_group}}"
    owner: "{{kafka_connect_user}}"
    mode: 0764

- name: Download Confluent Hub Tar
  get_url:
    url: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
    timeout: "{{kafka_connect_confluent_hub_client.timeout}}"
  when: kafka_connect_confluent_hub_client.is_remote

- name: Copy Confluent Hub Tar
  copy:
    src: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
  when: not kafka_connect_confluent_hub_client.is_remote

- name: Unarchiving Confluent Hub
  unarchive:
    src: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}"
    remote_src: true
    creates: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"

- name: Symlinking Confluent Hub CLI
  file:
    src: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"
    dest: "/usr/bin/confluent-hub"
    state: link

- name: "Installing Kafka Connect Connector(s) from Confluent Hub"
  shell: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub install --no-prompt --component-dir {{kafka_connect_confluent_hub_plugins_dest}} {{item}}"
  with_items: "{{kafka_connect_confluent_hub_plugins}}"
  when: kafka_connect_confluent_hub_plugins|length > 0
  notify: restart connect distributed

- name: Set Permissions on Plugin Folder(s)
  file:
    path: "{{ kafka_connect_confluent_hub_plugins_dest }}/{{ item.split(':')[0] | replace('/', '-') }}"
    owner: "{{kafka_connect_user}}"
    group: "{{kafka_connect_group}}"
    state: directory
    mode: 0750
  loop: "{{ kafka_connect_confluent_hub_plugins }}"
  when: kafka_connect_confluent_hub_plugins|length > 0

- name: Set Permissions on Plugin Files
  file:
    path: "{{ kafka_connect_confluent_hub_plugins_dest }}/{{ item.split(':')[0] | replace('/', '-') }}"
    owner: "{{kafka_connect_user}}"
    group: "{{kafka_connect_group}}"
    recurse: true
  loop: "{{ kafka_connect_confluent_hub_plugins }}"
  when: kafka_connect_confluent_hub_plugins|length > 0
