---
- name: Ensure Plugin Dirs
  file:
    path: "{{item}}"
    state: directory
    group: "{{kafka_connect_group}}"
    owner: "{{kafka_connect_user}}"
    mode: '764'
  when: item != '/usr/share/java'
  with_items: "{{ kafka_connect.properties['plugin.path'].split(',') }}"

- name: Installing Local Plugins
  unarchive:
    src: "{{item}}"
    dest: "{{kafka_connect_plugins_dest}}"
    remote_src: false
  with_items: "{{kafka_connect_plugins}}"
  when: kafka_connect_plugins|length > 0
  notify: restart connect distributed

- name: Installing Remote Plugins
  unarchive:
    src: "{{item}}"
    dest: "{{kafka_connect_plugins_dest}}"
    remote_src: true
  with_items: "{{kafka_connect_plugins_remote}}"
  when: kafka_connect_plugins_remote|length > 0
  notify: restart connect distributed

- name: Confluent Hub
  include_tasks: confluent_hub.yml
  when: kafka_connect_confluent_hub_install
