---
- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not kafka_connect_ssl_enabled|bool and not rbac_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: kafka_connect_ssl_enabled|bool and not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC - HTTP
  uri:
    url: "http://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    url_username: "{{kafka_connect_ldap_user}}"
    url_password: "{{kafka_connect_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not kafka_connect_ssl_enabled|bool and rbac_enabled|bool

- name: Wait for API to return 200 - RBAC - HTTPS
  uri:
    url: "https://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: no
    url_username: "{{kafka_connect_ldap_user}}"
    url_password: "{{kafka_connect_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: kafka_connect_ssl_enabled|bool and rbac_enabled|bool
