---
- name: Wait for API to return 200
  uri:
    url: "{{kafka_connect_http_protocol}}://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC - HTTPS
  uri:
    url: "{{kafka_connect_http_protocol}}://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: no
    url_username: "{{kafka_connect_ldap_user}}"
    url_password: "{{kafka_connect_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: rbac_enabled|bool
