---
# Cannot use Block/Rescue in Ansible Handlers: https://github.com/ansible/ansible/issues/14270
# Implementing try/catch logic with ignore_errors and conditionals
- name: Wait for API to return 200
  uri:
    url: "{{kafka_connect_replicator_http_protocol}}://{{ hostvars[inventory_hostname]|resolve_hostname }}:{{kafka_connect_replicator_port}}/connectors"
    status_code: 200
    validate_certs: false
    # Basic auth header is redundant for non rbac install
    url_username: "{{kafka_connect_replicator_health_check_user}}"
    url_password: "{{kafka_connect_replicator_health_check_password}}"
    force_basic_auth: true
  register: result1
  until: result1.status == 200
  retries: 30
  delay: 10
  when: not kafka_connect_replicator_ssl_mutual_auth_enabled|bool
  ignore_errors: true

- name: Wait for API to return 200 - mTLS
  uri:
    url: "{{kafka_connect_replicator_http_protocol}}://{{ hostvars[inventory_hostname]|resolve_hostname }}:{{kafka_connect_replicator_port}}/connectors"
    status_code: 200
    validate_certs: false
    client_cert: "{{kafka_connect_replicator_cert_path}}"
    client_key: "{{kafka_connect_replicator_key_path}}"
    # Basic auth header is redundant for non rbac install
    url_username: "{{kafka_connect_replicator_health_check_user}}"
    url_password: "{{kafka_connect_replicator_health_check_password}}"
    force_basic_auth: true
  register: result2
  until: result2.status == 200
  retries: 30
  delay: 10
  when: kafka_connect_replicator_ssl_mutual_auth_enabled|bool
  ignore_errors: true

- name: Fetch Log Files and Error out
  block:
    - name: Fetch Files for Debugging Failure
      # Cannot use include_role in Ansible Handlers: https://github.com/ansible/ansible/issues/20493
      include_tasks: ../../confluent.common/tasks/fetch_logs.yml
      vars:
        service_name: "{{kafka_connect_replicator_service_name}}"
        config_file: "{{kafka_connect_replicator.replication_config_file}}"
        log_dir: "{{ kafka_connect_replicator_log_dir|regex_replace('\\/$', '')}}"
        user: "{{kafka_connect_replicator_user}}"
        group: "{{kafka_connect_replicator_group}}"

    - name: Fail Provisioning
      fail:
        msg: Health checks failed. Review exported files.
  # When only one health check runs, only one will have a 'failed' field. For skipped checks, defaulting 'failed' to False
  when: result1.failed|default(False) or result2.failed|default(False)
