---
- name: Verify
  hosts: kafka_broker
  vars:
    test_topic_name: test
    test_message: "test message"
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-server.service.d/override.conf
      register: override_conf

    - name: Assert ownership on override.conf
      assert:
        that:
          - override_conf.stat.gr_name == "confluent"
          - override_conf.stat.pw_name == "cp-kafka"
        quiet: yes

    - name: Test topic creation
      shell: |
        kafka-topics --create --topic {{test_topic_name}} --bootstrap-server kafka_broker2:9092
      run_once: true
      changed_when: no

    - name: Test topic write
      shell: |
        echo '{{test_message}}' | kafka-console-producer --broker-list kafka_broker3:9092 --topic {{test_topic_name}}
      run_once: true
      changed_when: no

    - name: Test topic read
      shell: |
        timeout 4 kafka-console-consumer --topic {{test_topic_name}} \
          --from-beginning --bootstrap-server kafka_broker1:9092
      run_once: true
      changed_when: no
      register: output
      failed_when: "output.stdout != test_message"

    - name: Test topic deletion
      shell: kafka-topics --delete --topic test --bootstrap-server kafka_broker2:9092
      run_once: true
      changed_when: no
