---
- name: Gather OS Facts
  setup:
    filter: ansible_os_family
    gather_subset:
      - '!all'

- name: Install OpenSSL and Rsync - RedHat
  yum:
    name: "{{item}}"
    state: present
  loop:
    - openssl
    - rsync
  when: ansible_os_family == "RedHat"

- name: Install OpenSSL and Rsync - Debian
  apt:
    name: "{{item}}"
    state: present
  loop:
    - openssl
    - rsync
  when: ansible_os_family == "Debian"

- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create Certificate Authority
  shell: |
    openssl req -new -x509 \
      -keyout /var/ssl/private/generation/{{ssl_self_signed_ca_key_filename}} \
      -out /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -days 365 \
      -subj '/CN=ca1.test.confluent.io/OU=TEST/O=CONFLUENT/L=PaloAlto/S=Ca/C=US' \
      -passin pass:{{ssl_self_signed_ca_password}} -passout pass:{{ssl_self_signed_ca_password}}
  when:
    - self_signed|bool
    - regenerate_ca|bool
    - kafka_broker_listeners | ssl_required(ssl_enabled)

- name: Create MDS Private key
  shell: |
    openssl genrsa \
      -out /var/ssl/private/generation/{{token_services_private_pem_file|basename}} 2048
  when: create_mds_certs|bool

- name: Extract MDS Public key
  shell: |
    openssl rsa \
      -in /var/ssl/private/generation/{{token_services_private_pem_file|basename}} \
      -outform PEM -pubout \
      -out /var/ssl/private/generation/{{token_services_public_pem_file|basename}}
  when: create_mds_certs|bool

- name: Copy Generated SSL Files Back to Ansible Host
  synchronize:
    src: /var/ssl/private/generation/
    dest: generated_ssl_files
    mode: pull
    use_ssh_args: true

- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent
