---
# Run these tasks over kafka_broker group with serial: 1
# Creates two variable defined groups: non_controller_group, controller
# confluent_server_enabled must be set correctly for the host
- import_role:
    name: confluent.variables

- name: Load server.properties
  slurp:
    src: "{{ kafka_broker.config_file }}"
  register: slurped_properties

# TODO think thru the upgrade path, if secrets protection is enabled, but the zookeeper tls client properties file DNE
- name: Get Controller Broker ID
  shell: |
    {{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{zookeeper_client_port}} \
      {% if 'zookeeper.ssl.client.enable=true' in slurped_properties.content|b64decode %}-zk-tls-config-file {{kafka_broker.config_file}}{% endif %} \
      get /controller | grep brokerid
  register: controller_query
  run_once: true
  changed_when: false
  check_mode: false

- set_fact:
    controller_json: "{{controller_query.stdout}}"
    broker_id: "{{ (slurped_properties.content|b64decode).split('\n') | select('match', '^broker.id.*') | list | first | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1') }}"

- debug:
    msg: "Broker ID: {{broker_id}} and Controller ID: {{controller_json.brokerid}}"

- name: Add host to Non Controller Group
  add_host:
    name: "{{ inventory_hostname }}"
    group: "{{ non_controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int != controller_json.brokerid|int

- name: Add host to Controller Group
  add_host:
    name: "{{ inventory_hostname }}"
    group: "{{ controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int == controller_json.brokerid|int
