---
# Run these tasks over kafka_broker group with serial: 1
# Creates two variable defined groups: non_controller_group, controller
# confluent_server_enabled must be set correctly for the host
- import_role:
    name: confluent.variables

- name: Load server.properties
  slurp:
    src: "{{ kafka_broker.config_file }}"
  register: slurped_properties

# Zookeeper shell cannot read server.properties if secrets protection is enabled. Creates a non encrypted file
- name: Create Zookeeper TLS Client Config
  template:
    src: roles/confluent.kafka_broker/templates/zookeeper-tls-client.properties.j2
    dest: "{{kafka_broker.zookeeper_tls_client_config_file}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when:
    - "'zookeeper.ssl.client.enable = true' in slurped_properties.content|b64decode or 'zookeeper.ssl.client.enable=true' in slurped_properties.content|b64decode"
    - kafka_broker_secrets_protection_enabled|bool

- name: Get Controller Broker ID
  shell: |
    {{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{zookeeper_client_port}} \
      {% if 'zookeeper.ssl.client.enable = true' in slurped_properties.content|b64decode or 'zookeeper.ssl.client.enable=true' in slurped_properties.content|b64decode %}-zk-tls-config-file {{ kafka_broker.zookeeper_tls_client_config_file if kafka_broker_secrets_protection_enabled else kafka_broker.config_file }}{% endif %} \
      get /controller | grep brokerid
  register: controller_query
  run_once: true
  changed_when: false
  check_mode: false

- set_fact:
    controller_json: "{{controller_query.stdout}}"
    broker_id: "{{ (slurped_properties.content|b64decode).split('\n') | select('match', '^broker.id.*') | list | first | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1') }}"

- debug:
    msg: "Broker ID: {{broker_id}} and Controller ID: {{controller_json.brokerid}}"

- name: Add host to Non Controller Group
  add_host:
    name: "{{ hostname|default(ansible_host, true) }}"
    group: "{{ non_controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int != controller_json.brokerid|int

- name: Add host to Controller Group
  add_host:
    name: "{{ hostname|default(ansible_host, true) }}"
    group: "{{ controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int == controller_json.brokerid|int
