---
- name: Get Kafka Cluster ID from Zookeeper
  shell: /bin/zookeeper-shell localhost:2181 get /cluster/id | grep version
  delegate_to: "{{ groups['zookeeper'][0] }}"
  register: cluster_id_query

- set_fact:
    cluster_id_json: "{{ cluster_id_query.stdout }}"

- name: Set cluster_id Variable
  set_fact:
    kafka_cluster_id: "{{ cluster_id_json.id }}"
