---
- name: Create Passphrase File
  tags: masterkey
  shell: "openssl rand -base64 14 > /tmp/passphrase.txt"
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Generate Master Encryption Key and File
  tags: masterkey
  shell: |
    {{ confluent_cli_path }} secret master-key generate \
      --local-secrets-file /tmp/security.properties \
      --passphrase @/tmp/passphrase.txt | awk '/Master/{print $5}'
  register: masterkey
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Write Master Key to File
  tags: masterkey
  copy:
    content: "{{ masterkey.stdout }}"
    dest: /tmp/masterkey
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Copy Security File Back to Ansible Host
  tags: masterkey
  fetch:
    src: "/tmp/security.properties"
    dest: "{{secrets_protection_security_file}}"
    flat: true
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Copy Master Key Back to Ansible Host
  tags: masterkey
  fetch:
    src: /tmp/masterkey
    dest: "generated_ssl_files/"
    flat: true
  diff: "{{ not mask_sensitive_diff|bool }}"

- name: Remove Set Up Files
  tags: masterkey
  file:
    path: "/tmp/{{item}}"
    state: absent
  loop:
    - passphrase.txt
    - security.properties
    - masterkey
