---
- name: Set confluent_server_enabled Variable
  include_tasks: tasks/set_confluent_server_enabled.yml

- name: Search Override Conf Java Args for Jolokia Args with SSL Enabled
  shell: |
    grep "\{{kafka_broker_jolokia_java_arg_ssl_addon}}" {{ kafka_broker.systemd_override }}
  register: override_jolokia_ssl_enabled_search
  changed_when: false
  failed_when: false
  check_mode: false

- name: Search Jolokia Config with SSL Enabled
  shell: |
    grep 'protocol=https' {{ kafka_broker_jolokia_config }}
  register: config_jolokia_ssl_enabled_search
  changed_when: false
  # File may not exist
  failed_when: false
  check_mode: false

- name: Set kafka_broker_jolokia_ssl_enabled Variable to Proper value
  set_fact:
    kafka_broker_jolokia_ssl_enabled: "{{ (override_jolokia_ssl_enabled_search.rc == 0) or (config_jolokia_ssl_enabled_search.rc == 0) }}"
