---
- name: Get Package Facts
  package_facts:
    manager: auto

- set_fact:
    confluent_server_enabled: true
  when: ansible_facts.packages['confluent-server'] is defined

- set_fact:
    confluent_server_enabled: false
  when: ansible_facts.packages['confluent-kafka-2.12'] is defined or ansible_facts.packages['confluent-kafka'] is defined or ansible_facts.packages['confluent-kafka-2.11'] is defined

- set_fact:
    confluent_kafka_upgraded: true
  when: ansible_facts.packages['confluent-kafka'] is defined

- set_fact:
    confluent_kafka_upgraded: false
  when: ansible_facts.packages['confluent-kafka'] is not defined
