---
- name: Create Backup Directory
  file:
    # TODO configurable
    path: "/tmp/upgrade/{{ service_name }}"
    state: directory
    mode: 0640

- set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Backup Configuration files
  copy:
    src: "{{ item }}"
    remote_src: true
    dest: "/tmp/upgrade/{{ service_name }}/{{ item | basename }}-{{timestamp}}"
  loop: "{{ backup_files }}"
  # Files cannot be copied because directory is not created in check mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Stop Service
  systemd:
    name: "{{ service_name }}"
    state: stopped

- name: Configure Repositories
  import_role:
    name: confluent.common
  vars:
    install_java: false

- name: Remove Confluent-Kafka Packages - Red Hat
  yum:
    name: confluent-kafka-2.12
    state: absent
  when:
    - ansible_os_family == "RedHat"
    - not confluent_server_enabled|bool
  # Packages will not be found in check mode because repos not changed
  ignore_errors: "{{ ansible_check_mode }}"

- name: Remove Confluent-Kafka Packages - Debian
  apt:
    name: confluent-kafka-2.12
    state: absent
  when:
    - ansible_os_family == "Debian"
    - not confluent_server_enabled|bool
  # Packages will not be found in check mode because repos not changed
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install the Packages - Red Hat
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
    update_cache: true
  register: install_redhat_package_result
  until: install_redhat_package_result is success
  retries: 25
  delay: 5
  loop: "{{ packages }}"
  when: ansible_os_family == "RedHat"
  # Packages will not be found in check mode because repos not changed
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install the Packages - Debian
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
    update_cache: true
  register: install_debian_package_result
  until: install_debian_package_result is success
  retries: 25
  delay: 5
  loop: "{{ packages }}"
  when: ansible_os_family == "Debian"
  # Packages will not be found in check mode because repos not changed
  ignore_errors: "{{ ansible_check_mode }}"

- name: Put back configuration
  copy:
    dest: "{{ item }}"
    remote_src: true
    src: "/tmp/upgrade/{{ service_name }}/{{ item | basename }}-{{timestamp}}"
  loop: "{{ restore_files }}"
  # Files cannot be copied because directory is not created in check mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart Service
  systemd:
    daemon_reload: true
    name: "{{ service_name }}"
    state: restarted
