---
# Install Packages
- name: Install the Kafka Broker Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{kafka_broker_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Kafka Broker Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{kafka_broker_packages}}"
  when: ansible_os_family == "Debian"

- name: Install EPEL to gain access to additional tools
  yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present
  when: ansible_os_family == "RedHat" and rbac_enabled|bool 

- name: Install JQ to parse json on cmd line
  yum:
     name: jq
     state: latest
  when: ansible_os_family == "RedHat" and rbac_enabled|bool 

- name: Install JQ to parse json on cmd line
  apt:
     name: jq
     state: latest
  when: ansible_os_family == "Debian" and rbac_enabled|bool 

# Configure Environment
- name: Kafka Broker group
  group:
    name: "{{kafka_broker.group}}"

- name: Kafka Broker user
  user:
    name: "{{kafka_broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka_broker.group}}"

- import_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{kafka_broker_truststore_storepass}}"
    truststore_path: "{{kafka_broker_truststore_path}}"
    keystore_path: "{{kafka_broker_keystore_path}}"
    keystore_storepass: "{{kafka_broker_keystore_storepass}}"
    keystore_keypass: "{{kafka_broker_keystore_keypass}}"
  when: kafka_broker_listeners | ssl_required(ssl_enabled)

- name: Create pem file Directory
  file:
    path: "{{rbac_enabled_public_pem_path}}"
    group: "{{kafka_broker.group}}"
    mode: '650'
    recurse: yes
  when: rbac_enabled|bool 

- name: Copy in public pem files
  copy:
    src: "{{rbac_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  when: rbac_enabled|bool

- name: Copy in private pem files
  copy:
    src: "{{rbac_private_pem_file}}"
    dest: "{{rbac_enabled_private_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  when: rbac_enabled|bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{kafka_broker.group}}"
    mode: '650'
    recurse: yes
  when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms"

- name: Copy in Keytab File
  copy:
    src: "{{kafka_broker_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{kafka_broker_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms"
  notify:
    - Restart Kafka

- name: Create Kafka Broker Data Directories
  file:
    path: "{{item}}"
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
    state: directory
    mode: 0755
  with_items: "{{kafka_broker.datadir}}"

- name: Create Kafka Broker Config
  template:
    src: server.properties.j2
    dest: "{{kafka_broker.config_file}}"
    mode: 0640
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  notify:
    - Restart Kafka

- name: Create Logs Directory
  file:
    path: "{{kafka_broker.appender_log_path}}"
    group: "{{kafka_broker.group}}"
    owner: "{{kafka_broker.user}}"
    mode: '764'
    recurse: yes

- name: Create Kafka Broker log4j Config
  template:
    src: kafka_server_log4j.properties.j2
    dest: "{{kafka_broker.log4j_file}}"
    mode: 0640
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  notify:
    - Restart Kafka

- name: Create Kafka Broker Jaas Config
  template:
    src: kafka_server_jaas.conf.j2
    dest: "{{kafka_broker.jaas_file}}"
    mode: 0640
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms"
  notify:
    - Restart Kafka

- name: Create SCRAM Users
  shell: |
    kafka-configs --zookeeper localhost:2181 --alter \
      --add-config 'SCRAM-SHA-256=[password={{ item.value['password'] }}]' \
      --entity-type users --entity-name {{ item.value['principal'] }}
  loop: "{{ sasl_scram_users|dict2items }}"
  delegate_to: "{{ groups['zookeeper'][0] }}"
  run_once: true
  when: "'SCRAM-SHA-256' in kafka_broker_sasl_enabled_mechanisms"

- name: Deploy JMX Exporter Config File
  copy:
    src: "kafka.yml"
    dest: "{{jmxexporter_install_path}}/"
  when: jmxexporter_enabled|bool

- name: Create Service Override Directory
  file:
    path: "{{kafka_broker.systemd_override | dirname }}"
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{ kafka_broker.systemd_override }}"
    mode: 0640
    owner: "{{kafka_broker.user}}"
    group: "{{kafka_broker.group}}"
  notify:
    - reload systemd
    - Restart Kafka

- name: Tune virtual memory settings
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "{{ item.key }}.*"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ kafka_broker_sysctl }}"
  notify:
    - load sysctl

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: Restart Kafka
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Kafka Broker Service
  systemd:
    name: "{{kafka_broker_service_name}}"
    enabled: yes
    state: started
