---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_broker_service_name}}"
    state: restarted

- name: Wait for Under Replicated Partitions on Broker
  include_tasks: wait_for_urp.yml
  when:
    - health_checks_enabled|bool
    - jolokia_enabled|bool
    - not ansible_check_mode
