---
- name: Check if Kafka Service Running
  shell: "systemctl show -p SubState {{kafka_broker_service_name}}"
  changed_when: false
  register: substate

# All kafka_broker hosts iterate over the list of kakfa_broker hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Restart Kafka Serially
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['kafka_broker'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - substate.stdout == 'SubState=running'
    - not certs_updated|bool

- name: Restart Kafka in Parallel
  include: restart.yml
  when: substate.stdout != 'SubState=running' or certs_updated|bool
