---
- name: Set Principal - Sasl Scram
  set_fact:
    kafka_broker_principal: "{{ sasl_scram_users.admin.principal }}"
  when: kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'SCRAM-SHA-512'

- name: Set Principal - Sasl Plain
  set_fact:
    kafka_broker_principal: "{{ sasl_plain_users.admin.principal }}"
  when: kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'PLAIN'

- name: Set Principal - Sasl Kerberos
  set_fact:
    kafka_broker_principal: "{{ kerberos_kafka_broker_primary }}"
  when: kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Extract Common Name from Keystore - SSL Mutual Auth
  # Examine the keystore
  # Search lines with Entry type: "PrivateKeyEntry" and return that line and all after, ca cert is of type "trustedCertEntry"
  # Search for first "Owner" line
  # Extract DNAME from line
  # Remove spaces after commas
  shell: |
    keytool -list -keystore {{kafka_broker_keystore_path}} \
        -storepass {{kafka_broker_keystore_storepass}} -v \
        | grep PrivateKeyEntry -A1000 \
        | grep Owner -m1 \
        | cut -d ":" -f2 \
        | cut -c2- \
        | sed 's/\s*,\s*/,/g'
  register: distinguished_name_from_keystore
  when:
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'none'
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool
  no_log: "{{ mask_sensitive_logs|bool }}"

- name: Set Principal - SSL Mutual Auth
  set_fact:
    kafka_broker_principal: "{{ distinguished_name_from_keystore.stdout }}"
  when:
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'none'
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool
    - kafka_broker_listeners[kafka_broker_inter_broker_listener_name]['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool

- name: Normalize User Name
  set_fact:
    kafka_broker_principal: "User:{{ kafka_broker_principal }}"
  when: kafka_broker_principal is defined

- name: Validate that auth is set for RBAC on internal listener
  fail:
    msg: "Role Based Access Control (RBAC) requires that an authorization mechanism is set on the internal listener, please review Confluent documentation for further details."
  when: kafka_broker_principal is undefined
