- name: Copy in repo skip valid check
  copy:
    content: 'Acquire::Check-Valid-Until "0";'
    dest: /etc/apt/apt.conf.d/skip-check

- name: Add jessie-backports Repo
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main
    regexp: '.*jessie-backports.*'
  notify:
    - debian apt-get update

- meta: flush_handlers

- name: Install Java
  apt:
    name: "{{debian_java_package_name}}"
    state: present
    default_release: jessie-backports
  when: install_java

- name: Install rsync
  apt:
    name: rsync
    state: present
  with_items:
    - rsync
    - ca-certificates

- name: Install apt-transport-https
  shell: apt-get install apt-transport-https -y --force-yes
