- name: zookeeper create group
  group:
    name: "{{ zookeeper.group }}"
    state: present
  become: yes

- name: zookeeper create user
  user:
    name: "{{ zookeeper.user }}"
    comment: "Zookeeper User"
    system: yes
    group: "{{ zookeeper.group }}"
  become: yes

- name: Ensure zookeeper data directories are created
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ zookeeper.user }}"
    group: "{{ zookeeper.group }}"
    mode: 0750
  become: yes
  with_items:
    - "{{ zookeeper.config.dataDir }}"
    - "{{ zookeeper.config.dataLogDir }}"
  loop_control:
    loop_var: dir

- name: zookeeper myid file
  template:
    src: zookeeper/myid.j2
    dest: "{{ zookeeper.config.dataDir }}/myid"
    mode: 0555
    owner: "{{ zookeeper.user }}"
    group: "{{ zookeeper.group }}"
  become: yes
  notify: restart zookeeper

- name: zookeeper create config
  template:
    src: zookeeper/zookeeper.properties.j2
    dest: "{{ zookeeper.config_file }}"
    mode: 0400
    owner: "{{ zookeeper.user }}"
    group: "{{ zookeeper.group }}"
  become: yes
  notify: restart zookeeper

- name: zookeeper configure service
  systemd:
    name: "{{ zookeeper.service_name }}"
    enabled: "{{ zookeeper.systemd.enabled }}"
    state: "{{ zookeeper.systemd.state }}"
  become: yes
