zookeeper:
  properties:
    clientPort: 2181
kafka_port: 9092
kerberos:
  keytab_dir: /etc/security/keytabs
confluent:
  package_version: 5.3.1-1
  repo_version: 5.3
  support:
    customer_id: anonymous
    metrics_enabled: true

jolokia_jar_path: /opt/jolokia/jolokia.jar
zookeeper_jolokia_port: 7770
kafka_broker_jolokia_port: 7771
schema_registry_jolokia_port: 7772
kafka_connect_jolokia_port: 7773
ksql_jolokia_port: 7774
kafka_rest_jolokia_port: 7775

open_file_limit: 500000
