---
redhat_packages:
  - cyrus-sasl-gssapi
  - libselinux-python
  - krb5-libs
  - krb5-workstation


ubuntu_packages:
  - python-selinux
  - krb5-user
  - libsasl2-modules-gssapi-mit


dns_lookup_realm: "false"
dns_lookup_kdc: "false"
ticket_lifetime: "24h"
renew_lifetime: "7d"
forwardable: "true"
udp_preference_limit: 1000000
default_tkt_enctypes: des-cbc-md5 des-cbc-crc des3-cbc-sha1
default_tgs_enctypes: des-cbc-md5 des-cbc-crc des3-cbc-sha1
permitted_enctypes: des-cbc-md5 des-cbc-crc des3-cbc-sha1

realm_name: CONFLUENT.EXAMPLE.COM
kdc_hostname: ip-172-31-17-121.us-east-2.compute.internal
admin_hostname: ip-172-31-17-121.us-east-2.compute.internal