---
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Create Keytabs Directory
  file:
    path: /tmp/keytabs/
    state: directory
    mode: 0755

- name: "Add Principal: {{item.principal}}"
  shell: "kadmin.local -q 'addprinc -randkey {{item.principal}}'"
  loop: "{{ kerberos_principals }}"

- name: "Export Keytab for Principal: {{item.principal}}"
  shell: "kadmin.local -q 'xst -norandkey -k /tmp/keytabs/{{item.keytab_path | basename}} {{item.principal}}'"
  loop: "{{ kerberos_principals }}"

- name: Install Rsync
  yum:
    name: rsync

- name: Copy Keytabs Back to Ansible Host
  synchronize:
    src: /tmp/keytabs/
    dest: "{{keytab_output_directory}}"
    mode: pull
    use_ssh_args: true
