---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.internal.ssl.keystore.location
        expected_value: /var/ssl/private/kafka_broker.keystore.jks

    - name: Secrets Protection Test Variable 1
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: advertised.listeners
        expected_value: ${securepass:/var/ssl/private/security.properties:server.properties/advertised.listeners}

    - name: Secrets Protection Test Variable 2
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: broker.id
        expected_value: ${securepass:/var/ssl/private/security.properties:server.properties/broker.id}

    - name: Secrets Protection Test Variable 3
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: listener.name.internal.ssl.key.password
        expected_value: confluentkeystorestorepass

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/schema_registry.keystore.jks

    - name: Secrets Protection Test
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: kafkastore.ssl.key.password
        expected_value: ${securepass:/var/ssl/private/security.properties:schema-registry.properties/kafkastore.ssl.key.password}

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/kafka_rest.keystore.jks

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/kafka_connect.keystore.jks

    - name: Secrets Protection Test
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: value.converter.schema.registry.ssl.keystore.password
        expected_value: ${securepass:/var/ssl/private/security.properties:connect-distributed.properties/value.converter.schema.registry.ssl.keystore.password}

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ssl.keystore.location
        expected_value: /var/ssl/private/ksql.keystore.jks

    - name: Secrets Protection Test
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/security.properties:ksql-server.properties/ssl.truststore.password}

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.streams.ssl.keystore.location
        expected_value: /var/ssl/private/control_center.keystore.jks
