zookeeper_open_file_limit: "{{open_file_limit}}"

zookeeper_jaas_java_arg_buildout: "-Djava.security.auth.login.config={{zookeeper.jaas_file}}"
zookeeper_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{zookeeper_jolokia_port}},host=0.0.0.0"
zookeeper_log4j_java_arg_buildout: "-Dlog4j.configuration=file:{{zookeeper.log4j_file}}"
zookeeper_ssl_java_arg_buildout: "-Dzookeeper.serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory"

zookeeper_custom_log4j: "{{ custom_log4j }}"

zookeeper_custom_java_args: ""
zookeeper_java_args:
  - "{{ zookeeper_jaas_java_arg_buildout if 'GSSAPI' in kafka_broker_sasl_enabled_mechanisms else '' }}"
  - "{{ zookeeper_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"
  - "{{ zookeeper_log4j_java_arg_buildout if zookeeper_custom_log4j|bool else '' }}"
  - "{{ zookeeper_ssl_java_arg_buildout if zookeeper_ssl_enabled|bool else '' }}"

zookeeper_final_java_args: "{{ zookeeper_java_args + [ zookeeper_custom_java_args ] }}"

zookeeper_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx1g"
  KAFKA_OPTS: "{{ zookeeper_final_java_args | java_arg_build_out }}"
zookeeper_service_overrides:
  LimitNOFILE: "{{zookeeper_open_file_limit}}"

zookeeper:
  log_path: /var/log/kafka/
  log_name: zookeeper-server.log
  max_log_files: 10
  log_file_size: 100MB
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
