---
# More zookeeper variables are defined in the confluent.variables_handlers role

zookeeper_custom_log4j: "{{ custom_log4j }}"

zookeeper_java_args:
  - "{% if zookeeper_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if zookeeper_sasl_protocol in ['kerberos', 'digest'] %}-Djava.security.auth.login.config={{zookeeper.jaas_file}}{% endif %}"
  - "{% if zookeeper_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=port={{zookeeper_jolokia_port}},host=0.0.0.0{% endif %}"
  - "{% if zookeeper_custom_log4j|bool %}-Dlog4j.configuration=file:{{zookeeper.log4j_file}}{% endif %}"
  - "{% if zookeeper_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{zookeeper_jmxexporter_port}}:{{zookeeper_jmxexporter_config_path}}{% endif %}"

zookeeper_custom_java_args: ""
zookeeper_final_java_args: "{{ zookeeper_java_args + [ zookeeper_custom_java_args ] }}"

zookeeper_service_overrides:
  LimitNOFILE: 100000
  User: "{{ zookeeper_user if zookeeper_user != zookeeper_default_user else '' }}"
  Group: "{{ zookeeper_group if zookeeper_group != zookeeper_default_group else '' }}"
zookeeper_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx1g"
  KAFKA_OPTS: "{{ zookeeper_final_java_args | java_arg_build_out }}"

zookeeper:
  log_path: /var/log/kafka/
  log_name: zookeeper-server.log
  max_log_files: 10
  log_file_size: 100MB
