zookeeper:
  user: cp-kafka
  group: confluent
  config_file: /etc/kafka/zookeeper.properties
  service_name: confluent-zookeeper
  systemd_override: /etc/systemd/system/confluent-zookeeper.service.d
  jaas_file: /etc/kafka/zookeeper_jaas.conf
  keytab: /etc/security/keytabs
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
  environment:
    KAFKA_HEAP_OPTS: "-Xmx1000M"
  kerberosEnvironment:
    KAFKA_HEAP_OPTS: "-Xmx1000M"
    KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf"
  systemd:
    enabled: yes
    state: started
  packages:
    - "confluent-kafka-2.12-{{confluent.package_version}}"
    - "confluent-security-{{confluent.package_version}}"
