zookeeper_open_file_limit: "{{open_file_limit}}"

zookeeper_jaas_file: /etc/kafka/zookeeper_jaas.conf
zookeeper_jaas_java_arg_buildout: "-Djava.security.auth.login.config={{zookeeper_jaas_file}}"
zookeeper_jaas_java_arg: "{{ zookeeper_jaas_java_arg_buildout if security_mode in ['kerberos', 'kerberos_ssl', 'kerberos_ssl_customcerts'] else '' }}"

zookeeper_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{zookeeper_jolokia_port}},host=0.0.0.0"
zookeeper_jolokia_java_arg: "{{ zookeeper_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

zookeeper_kafka_opts_buildout: "{{ zookeeper_jolokia_java_arg + ' ' + zookeeper_jaas_java_arg if zookeeper_jolokia_java_arg != '' or zookeeper_jaas_java_arg != '' else '' }}"

zookeeper_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx1g"
  KAFKA_OPTS: "{{ zookeeper_kafka_opts_buildout }}"
zookeeper_service_overrides:
  LimitNOFILE: "{{zookeeper_open_file_limit}}"

zookeeper:
  # keytab: /etc/security/keytabs
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
