---
- name: get uuid
  shell: "{{ binary_base_path }}/bin/kafka-storage random-uuid"
  environment:
    KAFKA_OPTS: "-Xlog:all=error -XX:+IgnoreUnrecognizedVMOptions"
  register: uuid_key
  run_once: true

- name: get CLUSTER_ID
  set_fact:
    clusterid: "{{ uuid_key.stdout }}"

- name: format meta directory
  shell: "{{ binary_base_path }}/bin/kafka-storage  format -t {{ clusterid }} -c {{ kafka_controller.config_file }}  --ignore-formatted"
  register: format_meta
