---
- name: Get Kafka Cluster Id
  import_tasks: rbac_setup.yml
  vars:
    copy_certs: false

- name: Register Kafka Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    # For audit logs, must register the oauth listener which will be the "internal" listener
    body: >
      [
          {
              "clusterName": "{{kafka_controller_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}"
                  }
              },
              "hosts": [ {% for host in groups['kafka_controller'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{kafka_controller_listeners.internal.port}} }{% endfor %}
              ],
              "protocol": "{{kafka_controller_listeners.internal.sasl_protocol|default(sasl_protocol) | confluent.platform.kafka_protocol(kafka_controller_listeners.internal.ssl_enabled|default(ssl_enabled)) }}"
          }
      ]
    status_code: 204
  run_once: true
  register: output
