---
# More kafka_rest variables are defined in the confluent.variables role

kafka_rest_java_args:
  - "{% if kafka_rest_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if kafka_rest_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=config={{kafka_rest_jolokia_config}}{% endif %}"
  - "{% if kafka_rest_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{kafka_rest_jmxexporter_port}}:{{kafka_rest_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the Rest Proxy Process
kafka_rest_custom_java_args: ""

kafka_rest_final_java_args: "{{ kafka_rest_java_args + [ kafka_rest_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
kafka_rest_service_overrides:
  User: "{{ kafka_rest_user if kafka_rest_user != kafka_rest_default_user else '' }}"
  Group: "{{ kafka_rest_group if kafka_rest_group != kafka_rest_default_group else '' }}"
  ExecStart: "{% if installation_method == 'archive' %}{{ kafka_rest.server_start_file }} {{ kafka_rest.config_file }}{% endif %}"

# Key/Value Pairs with empty values will not be written into override.conf
kafka_rest_service_environment_overrides:
  KAFKAREST_HEAP_OPTS: "-Xms1g -Xmx1g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
  KAFKAREST_OPTS: "{{ kafka_rest_final_java_args | java_arg_build_out }}"
  # Remove trailing slash if there is one
  LOG_DIR: "{{ kafka_rest_log_dir|regex_replace('\\/$', '') if kafka_rest_log_dir|regex_replace('\\/$', '') != kafka_rest_default_log_dir else '' }}"
  CONFLUENT_SECURITY_MASTER_KEY: "{% if kafka_rest_secrets_protection_enabled|bool %}{{secrets_protection_masterkey}}{% endif %}"

### Time in seconds to wait before starting Rest Proxy Health Checks.
kafka_rest_health_check_delay: 20
