kafka_rest_open_file_limit: "{{open_file_limit}}"

kafka_rest_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{kafka_rest_jolokia_port}},host=0.0.0.0"
kafka_rest_log4j_java_arg_buildout: "-Dlog4j.configuration=file:{{kafka_rest.log4j_file}}"

kafka_rest_custom_log4j: "{{ custom_log4j }}"

kafka_rest_custom_java_args: ""
kafka_rest_java_args:
  - "{{ kafka_rest_jolokia_java_arg_buildout if kafka_rest_jolokia_enabled|bool else '' }}"
  - "{{ kafka_rest_ssl_java_arg_buidout if schema_registry_ssl_enabled|bool else '' }}"
  - "{{ kafka_rest_log4j_java_arg_buildout if kafka_rest_custom_log4j|bool else '' }}"

kafka_rest_final_java_args: "{{ kafka_rest_java_args + [ kafka_rest_custom_java_args ] }}"

kafka_rest_service_overrides:
  LimitNOFILE: "{{kafka_rest_open_file_limit}}"
kafka_rest_service_environment_overrides:
  LOG_DIR: /var/log/kafka-rest
  KAFKAREST_OPTS: "{{ kafka_rest_final_java_args | java_arg_build_out }}"

kafka_rest:
  appender_log_path: /var/log/rest-proxy/
  appender_log_name: rest-proxy.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
  properties:
    id: "{{groups.kafka_rest.index(inventory_hostname) + 1}}"
