---
galaxy_info:
  author: Confluent
  description: This is role for setting up Connect Replicator
  company: Confluent
  license: Apache-2.0
  min_ansible_version: '2.14.0'
dependencies:
  - role: variables
