---
- name: RBAC Setup Tasks
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    user: "{{control_center_user}}"
    group: "{{control_center_group}}"

- name: Grant role System Admin to Additional Control Center super users
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{item}}/roles/SystemAdmin"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}"
        }
      }
    status_code: 204
  register: admin_role_response
  until: admin_role_response.status == 204
  retries: 5
  delay: 10
  loop: "{{control_center_additional_system_admins}}"
  when: not ansible_check_mode

- name: Grant role System Admin to Control Center user
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{control_center_ldap_user}}/roles/SystemAdmin"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}"
        }
      }
    status_code: 204
  when: not ansible_check_mode
