- name: yum-clean-all
  command: yum clean all
  args:
    warn: no
  when: ansible_os_family == "RedHat"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart connect distributed
  systemd:
    name: "{{ kafka.connect.distributed.service_name }}"
    state: restarted

- name: restart control center
  systemd:
    name: "{{ confluent.control.center.service_name }}"
    state: restarted

- name: restart kafka
  systemd:
    name: "{{ kafka.broker.service_name }}"
    state: restarted

- name: restart kafka-rest
  systemd:
    name: "{{ kafkarest.service_name }}"
    state: restarted

- name: restart ksql
  systemd:
    name: "{{ ksql.service_name }}"
    state: restarted

- name: restart schema-registry
  systemd:
    name: "{{ schema.registry.service_name }}"
    state: restarted

- name: restart zookeeper
  systemd:
    name: "{{ zookeeper.service_name }}"
    state: restarted
