---
### Validates that Java 11 is in use.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Java Version
      shell: java -version
      register: version_output

    - name: Assert Java Version is 11
      assert:
        that:
          - version_output.stderr_lines[0] | regex_search("11\.0\.")
        fail_msg: "Current Java Version is: {{version_output.stderr_lines[0]}} Should be 11"
        quiet: true
