- name: schema-registry create group
  group:
    name: "{{ schema.registry.group }}"
  become: yes

- name: schema-registry create user
  user:
    name: "{{ schema.registry.user }}"
    comment: "Schema Registry User"
    system: yes
    group: "{{ schema.registry.group }}"
  become: yes

- name: schema-registry create config
  template:
    src: schema-registry/schema-registry.properties.j2
    dest: "{{ schema.registry.config_file }}"
    mode: 0640
    owner: "{{ schema.registry.user }}"
    group: "{{ schema.registry.group }}"
  notify:
    - restart schema-registry
  become: yes

- name: Schema registry add env var to service file
  ini_file:
    path: /usr/lib/systemd/system/confluent-schema-registry.service
    section: Service
    # Mind the quote in option and option ! We want it to be a quoted string in the target file
    option: "Environment='{{ var.key }}"
    value: "{{ var.value }}'"
    no_extra_spaces: yes
  with_dict: "{{ schema.registry.environment }}"
  loop_control:
    loop_var: var
  notify: reload systemd
  become: yes

- name: schema-registry configure service
  systemd:
    name: "{{ schema.registry.service_name }}"
    enabled: "{{ schema.registry.systemd.enabled }}"
    state: "{{ schema.registry.systemd.state }}"
  become: yes

- name: Flush handlers
  meta: flush_handlers
