---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

# Install Packages
- name: Install the Control Center Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Control Center Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Control Center Group
  group:
    name: "{{control_center_group}}"

- name: Create Control Center User
  user:
    name: "{{control_center_user}}"
    comment: "Control Center User"
    system: true
    group: "{{control_center_group}}"

- name: Set Control Center Data Dir permissions
  file:
    path: "{{control_center.properties['confluent.controlcenter.data.dir']}}"
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
    state: directory
    mode: 0755

- name: Set Control Center Data Dir file permissions
  file:
    path: "{{control_center.properties['confluent.controlcenter.data.dir']}}"
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
    recurse: true

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{control_center_truststore_storepass}}"
    truststore_path: "{{control_center_truststore_path}}"
    keystore_path: "{{control_center_keystore_path}}"
    keystore_storepass: "{{control_center_keystore_storepass}}"
    keystore_keypass: "{{control_center_keystore_keypass}}"
    service_name: control_center
    hostnames: "{{ [inventory_hostname, ansible_fqdn, ansible_host, ansible_ssh_host] | unique }}"
  when: control_center_ssl_enabled|bool or kafka_broker_listeners[control_center_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{control_center_group}}"
    kerberos_user: "{{control_center_user}}"
    kerberos_keytab_path: "{{control_center_kerberos_keytab_path}}"
    kerberos_handler: "restart control center"
  when: kafka_broker_listeners[control_center_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Create Control Center Config
  template:
    src: control-center.properties.j2
    dest: "{{control_center.config_file}}"
    mode: 0640
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
  notify: restart control center

- name: Set Permissions on /var/log/confluent
  file:
    path: /var/log/confluent/
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"

- name: Create Logs Directory
  file:
    path: "{{control_center.appender_log_path}}"
    state: directory
    group: "{{control_center_group}}"
    owner: "{{control_center_user}}"
    mode: 0770

- name: Create RocksDB Directory
  file:
    path: "{{control_center_rocksdb_path}}"
    group: "{{control_center_group}}"
    owner: "{{control_center_user}}"
    mode: '764'
    state: directory
  when: control_center_rocksdb_path != ""

- name: Set Permission to RocksDB Files
  file:
    path: "{{control_center_rocksdb_path}}"
    group: "{{control_center_group}}"
    owner: "{{control_center_user}}"
    recurse: true
  when: control_center_rocksdb_path != ""

- name: Create Control Center log4j Config
  template:
    src: control-center_log4j.properties.j2
    dest: "{{control_center.log4j_file}}"
    mode: 0640
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
  notify: restart control center

- name: Create Service Override Directory
  file:
    path: "{{control_center.systemd_override | dirname}}"
    state: directory
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{control_center.systemd_override}}"
    mode: 0640
    owner: root
    group: root
  notify: restart control center

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart control center
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Control Center Service
  systemd:
    name: "{{control_center_service_name}}"
    enabled: true
    state: started

- name: Health Check
  include_tasks: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
