---
- name: Remove the Zookeeper, Kafka Broker, Schema Registry and Kafka Rest Groups from Inventory
  hosts: zookeeper:kafka_broker:schema_registry:kafka_rest
  gather_facts: false
  tasks:
    - name: "Change {{item}} Group Name in Inventory File for MDS"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "{{item}}:"
        line: "{{item}}_mds:"
      delegate_to: 127.0.0.1
      run_once: true
      loop:
        - zookeeper
        - kafka_broker

    - name: "Change {{item}} Group Name in Inventory File for cluster2"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "{{item}}2:"
        line: "{{item}}:"
      delegate_to: 127.0.0.1
      run_once: true
      loop:
        - zookeeper
        - kafka_broker
        - kafka_connect_replicator

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Converge
  import_playbook: ../../../../all.yml
