---
skip_properties:
  - bootstrap.servers
  - confluent.controlcenter.connect.connect-cluster.cluster
  - confluent.controlcenter.ksql.ksql.advertised.url
  - confluent.controlcenter.ksql.ksql.url
  - confluent.controlcenter.schema.registry.url
  - confluent.controlcenter.streams.cprest.url
  - confluent.controlcenter.streams.num.stream.threads
  - confluent.controlcenter.streams.sasl.jaas.config
  - confluent.controlcenter.streams.sasl.mechanism
  - confluent.controlcenter.streams.security.protocol
  - confluent.monitoring.interceptor.sasl.mechanism
  - confluent.monitoring.interceptor.security.protocol
  - confluent.monitoring.interceptor.sasl.jaas.config
  - confluent.controlcenter.schema.registry.schema.registry.ssl.truststore.location
  - confluent.controlcenter.schema.registry.schema.registry.ssl.truststore.password
  - confluent.controlcenter.schema.registry.schema.registry.ssl.keystore.location
  - confluent.controlcenter.schema.registry.schema.registry.ssl.keystore.password
  - confluent.controlcenter.schema.registry.schema.registry.ssl.key.password
  - confluent.controlcenter.connect.connect-cluster.ssl.key.password
  - confluent.controlcenter.connect.connect-cluster.ssl.keystore.location
  - confluent.controlcenter.connect.connect-cluster.ssl.keystore.password
  - confluent.controlcenter.connect.connect-cluster.ssl.truststore.location
  - confluent.controlcenter.connect.connect-cluster.ssl.truststore.password
  - confluent.controlcenter.ksql.ksql.ssl.key.password
  - confluent.controlcenter.ksql.ksql.ssl.keystore.location
  - confluent.controlcenter.ksql.ksql.ssl.keystore.password
  - confluent.controlcenter.ksql.ksql.ssl.truststore.location
  - confluent.controlcenter.ksql.ksql.ssl.truststore.password
  - confluent.controlcenter.streams.ssl.truststore.location
  - confluent.controlcenter.streams.ssl.truststore.password
  - confluent.controlcenter.streams.ssl.key.password
  - confluent.controlcenter.streams.ssl.keystore.location
  - confluent.controlcenter.streams.ssl.keystore.password
  - confluent.monitoring.interceptor.ssl.truststore.location
  - confluent.monitoring.interceptor.ssl.truststore.password
  - confluent.monitoring.interceptor.ssl.key.password
  - confluent.monitoring.interceptor.ssl.keystore.location
  - confluent.monitoring.interceptor.ssl.keystore.password
  - confluent.controlcenter.schema.registry.basic.auth.credentials.source
  - confluent.controlcenter.rest.authentication.realm
  - confluent.controlcenter.auth.restricted.roles
  - confluent.controlcenter.auth.session.expiration.ms
  - confluent.metadata.ssl.truststore.location
  - confluent.metadata.ssl.truststore.password
  - confluent.metadata.ssl.endpoint.identification.algorithm
  - confluent.metadata.http.auth.credentials.provider
  - confluent.controlcenter.streams.sasl.login.callback.handler.class
  - confluent.monitoring.interceptor.sasl.login.callback.handler.class
  - client.sasl.login.callback.handler.class
  - config.providers
  - config.providers.securepass.class
  - confluent.telemetry.enabled
  - confluent.telemetry.api.key
  - confluent.telemetry.api.secret
  - confluent.telemetry.proxy.url
  - confluent.telemetry.proxy.username
  - confluent.telemetry.proxy.password
  - metric.reporters
  - confluent.controlcenter.streams.sasl.kerberos.service.name
  - confluent.monitoring.interceptor.sasl.kerberos.service.name
  - confluent.controlcenter.schema.registry.enable
  - confluent.controlcenter.schema.registry.sr-cluster.url
  - confluent.controlcenter.ksql.default.advertised.url
  - confluent.controlcenter.ksql.default.url
  - confluent.controlcenter.ksql.enable
  - confluent.controlcenter.connect.default.cluster
  - confluent.controlcenter.kafka.destination.bootstrap.servers
  - confluent.controlcenter.kafka.origin.bootstrap.servers

