skip_properties:
  - consumer.confluent.monitoring.interceptor.bootstrap.servers
  - consumer.interceptor.classes
  - producer.confluent.monitoring.interceptor.bootstrap.servers
  - producer.interceptor.classes
  - sasl.jaas.config
  - bootstrap.servers
  - sasl.jaas.config
  - ssl.truststore.location
  - ssl.truststore.password
  - confluent.monitoring.interceptor.topic
  - consumer.confluent.monitoring.interceptor.bootstrap.servers
  - consumer.interceptor.classes
  - producer.confluent.monitoring.interceptor.bootstrap.servers
  - producer.interceptor.classes
  - confluent.license.topic
  - sasl.kerberos.service.name
  - sasl.mechanism
  - security.protocol
  - config.providers
  - config.providers.securepass.class
