skip_properties:
  - bootstrap.servers
  - client.confluent.monitoring.interceptor.bootstrap.servers
  - client.confluent.monitoring.interceptor.sasl.jaas.config
  - client.confluent.monitoring.interceptor.sasl.mechanism
  - client.confluent.monitoring.interceptor.security.protocol
  - client.sasl.jaas.config
  - client.sasl.mechanism
  - client.security.protocol
  - confluent.license.topic
  - confluent.monitoring.interceptor.topic=_confluent-monitoring
  - consumer.interceptor.classes
  - producer.interceptor.classes
  - host.name
  - id
  - schema.registry.url
  - schema.registry.ssl.key.password
  - schema.registry.ssl.keystore.location
  - schema.registry.ssl.keystore.password
  - schema.registry.ssl.truststore.location
  - schema.registry.ssl.truststore.password
  - authentication.realm
  - client.ssl.truststore.location
  - client.ssl.truststore.password
  - client.ssl.key.password
  - client.ssl.keystore.location
  - client.ssl.keystore.password
  - client.confluent.monitoring.interceptor.ssl.truststore.location
  - client.confluent.monitoring.interceptor.ssl.truststore.password
  - client.confluent.monitoring.interceptor.ssl.key.password
  - client.confluent.monitoring.interceptor.ssl.keystore.location
  - client.confluent.monitoring.interceptor.ssl.keystore.password
  - client.config.providers.securepass.class
  - basic.auth.credentials.source
  - rest.servlet.initializor.classes
  - confluent.metadata.http.auth.credentials.provider
  - ssl.truststore.location
  - ssl.truststore.password
  - confluent.metadata.ssl.truststore.location
  - confluent.metadata.ssl.truststore.password
  - confluent.metadata.ssl.endpoint.identification.algorithm
  - client.confluent.monitoring.interceptor.sasl.login.callback.handler.class
  - client.sasl.login.callback.handler.class
  - config.providers
  - config.providers.securepass.class
  - confluent.telemetry.enabled
  - confluent.telemetry.api.key
  - confluent.telemetry.api.secret
  - confluent.telemetry.proxy.url
  - confluent.telemetry.proxy.username
  - confluent.telemetry.proxy.password
  - metric.reporters
