skip_properties:
# Written by Ansible
  - bootstrap.servers
  - config.providers.secret.param.kafkastore.sasl.jaas.config
  - config.providers.secret.param.kafkastore.sasl.mechanism
  - config.providers.secret.param.kafkastore.security.protocol
  - confluent.license.topic
  - consumer.bootstrap.servers
  - consumer.confluent.monitoring.interceptor.bootstrap.servers
  - consumer.confluent.monitoring.interceptor.sasl.jaas.config
  - consumer.confluent.monitoring.interceptor.sasl.mechanism
  - consumer.confluent.monitoring.interceptor.security.protocol
  - consumer.interceptor.classes
  - consumer.sasl.jaas.config
  - consumer.sasl.mechanism
  - consumer.security.protocol
  - internal.key.converter
  - internal.key.converter.schemas.enable
  - internal.value.converter
  - internal.value.converter.schemas.enable
  - key.converter
  - key.converter.schema.registry.url
  - offset.flush.interval.ms
  - offset.storage.replication.factor
  - offset.storage.topic
  - producer.bootstrap.servers
  - producer.confluent.monitoring.interceptor.bootstrap.servers
  - producer.confluent.monitoring.interceptor.sasl.jaas.config
  - producer.confluent.monitoring.interceptor.sasl.mechanism
  - producer.confluent.monitoring.interceptor.security.protocol
  - producer.interceptor.classes
  - producer.sasl.jaas.config
  - producer.sasl.mechanism
  - producer.security.protocol
  - rest.advertised.host.name
  - rest.port
  - sasl.jaas.config
  - sasl.mechanism
  - security.protocol
  - status.storage.replication.factor
  - status.storage.topic
  - value.converter
  - value.converter.schema.registry.url
  - key.converter.schema.registry.url
  - value.converter.schema.registry.ssl.truststore.location
  - value.converter.schema.registry.ssl.truststore.password
  - value.converter.schema.registry.ssl.keystore.location
  - value.converter.schema.registry.ssl.keystore.password
  - value.converter.schema.registry.ssl.key.password
  - key.converter.schema.registry.ssl.truststore.location
  - key.converter.schema.registry.ssl.truststore.password
  - key.converter.schema.registry.ssl.keystore.location
  - key.converter.schema.registry.ssl.keystore.password
  - key.converter.schema.registry.ssl.key.password
  - rest.advertised.listener
  - value.converter.basic.auth.credentials.source
  - key.converter.basic.auth.credentials.source
  - consumer.confluent.monitoring.interceptor.ssl.truststore.location
  - consumer.confluent.monitoring.interceptor.ssl.truststore.password
  - consumer.confluent.monitoring.interceptor.ssl.key.password
  - consumer.confluent.monitoring.interceptor.ssl.keystore.location
  - consumer.confluent.monitoring.interceptor.ssl.keystore.password
  - consumer.ssl.truststore.location
  - consumer.ssl.truststore.password
  - consumer.ssl.key.password
  - consumer.ssl.keystore.location
  - consumer.ssl.keystore.password
  - producer.confluent.monitoring.interceptor.ssl.truststore.location
  - producer.confluent.monitoring.interceptor.ssl.truststore.password
  - producer.confluent.monitoring.interceptor.ssl.key.password
  - producer.confluent.monitoring.interceptor.ssl.keystore.location
  - producer.confluent.monitoring.interceptor.ssl.keystore.password
  - producer.ssl.truststore.location
  - producer.ssl.truststore.password
  - producer.ssl.key.password
  - producer.ssl.keystore.location
  - producer.ssl.keystore.password
  - config.providers.secret.param.kafkastore.ssl.key.password
  - config.providers.secret.param.kafkastore.ssl.keystore.location
  - config.providers.secret.param.kafkastore.ssl.keystore.password
  - config.providers.secret.param.kafkastore.ssl.truststore.location
  - config.providers.secret.param.kafkastore.ssl.truststore.password
  - confluent.metadata.http.auth.credentials.provider
  - ssl.truststore.location
  - ssl.truststore.password
  - confluent.metadata.ssl.truststore.location
  - confluent.metadata.ssl.truststore.password
  - confluent.metadata.ssl.endpoint.identification.algorithm
  - config.providers.secret.class
  - config.providers.secret.param.kafkastore.topic
  - config.providers.secret.param.secret.registry.group.id
  - ssl.key.password
  - ssl.keystore.location
  - ssl.keystore.password
  - connector.client.config.override.policy
  - config.providers.secret.param.kafkastore.bootstrap.servers
  - config.providers.secret.param.kafkastore.sasl.login.callback.handler.class
  - consumer.confluent.monitoring.interceptor.sasl.login.callback.handler.class
  - consumer.sasl.login.callback.handler.class
  - producer.confluent.monitoring.interceptor.sasl.login.callback.handler.class
  - producer.sasl.login.callback.handler.class
  - rest.extension.classes
  - sasl.login.callback.handler.class
  - config.providers
  - config.providers.securepass.class
