---
skip_properties:
  - confluent.license.topic
  - debug
  - host.name
  - kafkastore.bootstrap.servers
  - kafkastore.sasl.jaas.config
  - kafkastore.sasl.mechanism
  - kafkastore.security.protocol
  - security.protocol
  - kafkastore.ssl.truststore.location
  - kafkastore.ssl.truststore.password
  - kafkastore.ssl.key.password
  - kafkastore.ssl.keystore.location
  - kafkastore.ssl.keystore.password
  - authentication.realm
  - authentication.roles
  - schema.registry.resource.extension.class
  - rest.servlet.initializor.classes
  - confluent.schema.registry.auth.mechanism
  - confluent.metadata.ssl.truststore.location
  - confluent.metadata.ssl.truststore.password
  - confluent.metadata.ssl.endpoint.identification.algorithm
  - confluent.metadata.http.auth.credentials.provider
  - kafkastore.sasl.login.callback.handler.class
  - config.providers
  - config.providers.securepass.class
  - confluent.telemetry.enabled
  - confluent.telemetry.api.key
  - confluent.telemetry.api.secret
  - confluent.telemetry.proxy.url
  - confluent.telemetry.proxy.username
  - confluent.telemetry.proxy.password
  - metric.reporters
  - kafkastore.sasl.kerberos.service.name

