- name: broker group
  group:
    name: "{{kafka.broker.group}}"
- name: broker user
  user:
    name: "{{kafka.broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka.broker.group}}"
- name: create broker data directories
  file:
    path: "{{item}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0755
  loop: "{{kafka.broker.datadir}}"
- name: broker plaintext config
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart kafka
- name: broker ssl config
  template:
    src: server_ssl.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "ssl"
  notify:
    - restart kafka
- name: broker sasl_ssl config
  template:
    src: server_sasl_ssl.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart kafka
- name: broker configure service
  systemd:
    name: "{{kafka.broker.service_name}}"
    enabled: "{{kafka.broker.systemd.enabled}}"
    state: "{{kafka.broker.systemd.state}}"
