- name: broker group
  group:
    name: "{{kafka.broker.group}}"
- name: broker user
  user:
    name: "{{kafka.broker.user}}"
    comment: "Kafka User"
    system: yes
    group: "{{kafka.broker.group}}"
- name: Change keytabs ownership
  file:
    path: "{{kafka.broker.keytab}}"
    group: "{{kafka.broker.group}}"
    mode: '650'
    recurse: yes
- name: create broker data directories
  file:
    path: "{{item}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0755
  with_items: "{{kafka.broker.datadir}}"
- name: broker plaintext config
  template:
    src: server.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart kafka
- name: broker ssl config
  template:
    src: server_ssl.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "ssl"
  notify:
    - restart kafka
- name: broker sasl_ssl config
  template:
    src: server_sasl_ssl.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart kafka
- name: broker ssl custom signed config
  template:
    src: server_ssl_self_signed.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "ssl_customcerts"
  notify:
    - restart kafka
- name: broker gssapi kerberos config
  template:
    src: server_kerberos.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "kerberos"
  notify:
    - restart kafka
- name: broker ssl kerberos config
  template:
    src: server_kerberos_ssl.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "kerberos_ssl"
  notify:
    - restart kafka
- name: broker ssl kerberos config
  template:
    src: server_kerberos_ssl.self_signed.properties.j2
    dest: "{{kafka.broker.config_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "kerberos_ssl_customcerts"
  notify:
    - restart kafka
- name: broker Jaas config
  template:
    src: kafka_server_jaas.conf.j2
    dest: "{{kafka.broker.jaas_file}}"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts"
  notify:
    - restart kafka
- name: create systemd override file
  file:
    path: "{{kafka.broker.systemd_override}}"
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
    state: directory
    mode: 0640
- name: write environment variables
  template:
    src: environment.j2
    dest: "{{kafka.broker.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "plaintext" or security_mode == "sasl_ssl" or security_mode == "ssl_customcerts"
  notify:
    - reload systemd
    - restart kafka
- name: write environment variables
  template:
    src: kerberosenvironment.j2
    dest: "{{kafka.broker.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{kafka.broker.user}}"
    group: "{{kafka.broker.group}}"
  when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts"
  notify:
    - reload systemd
    - restart kafka
- name: broker configure service
  systemd:
    name: "{{kafka.broker.service_name}}"
    enabled: "{{kafka.broker.systemd.enabled}}"
    state: "{{kafka.broker.systemd.state}}"


