---
- name: Create Custom Certs
  import_playbook: ../certificates.yml

- name: Provision LDAP Server
  import_playbook: ../ldap.yml

- name: Provision Kerberos Server
  import_playbook: ../kerberos.yml

- name: Install MDS Cluster
  import_playbook: ../../../../all.yml

# - name: Create Topics and Data for Replication on Source Cluster
#   import_playbook: topic_data_creation.yml
