schema:
  registry:
    user: cp-schema-registry
    group: confluent
    config_file: /etc/schema-registry/schema-registry.properties
    service_name: confluent-schema-registry
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
    systemd:
      enabled: yes
      state: started
