---
- name: Download Root CAs for Confluent Cloud
  get_url:
    url: "https://letsencrypt.org/certs/{{item}}"
    dest: /tmp/{{item}}
    mode: 0755
  loop:
    - isrgrootx1.der
    - isrg-root-x2.der
    - lets-encrypt-r3-cross-signed.der
    - lets-encrypt-r4-cross-signed.der
    - lets-encrypt-e1.der
    - lets-encrypt-e2.der

- name: Add Root CAs to KSQL Truststore
  java_cert:
    cert_path: "/tmp/{{item}}.der"
    keystore_path: "{{ksql_truststore_path}}"
    keystore_pass: "{{ksql_truststore_storepass}}"
    cert_alias: "{{item}}"
    trust_cacert: true
  loop:
    - isrgrootx1
    - isrg-root-x2
    - lets-encrypt-r3-cross-signed
    - lets-encrypt-r4-cross-signed
    - lets-encrypt-e1
    - lets-encrypt-e2

- name: Delete Certificates
  file:
    path: "/tmp/{{item}}"
    state: absent
  loop:
    - isrgrootx1.der
    - isrg-root-x2.der
    - lets-encrypt-r3-cross-signed.der
    - lets-encrypt-r4-cross-signed.der
    - lets-encrypt-e1.der
    - lets-encrypt-e2.der
