---
keystore_expiration_days: 365
delete_generation_dir: true

ca_key_path: "{{ ssl_file_directory }}generation/ca.key"

ssl_custom_certs_remote_src: false

### Key Algorithm used by keytool -genkeypair command when creating Keystores. Only used with self-signed certs
ssl_key_algorithm: RSA

### Key Size used by keytool -genkeypair command when creating Keystores. Only used with self-signed certs
ssl_key_size: 2048

create_bouncy_castle_keystore: false
