---
driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker1
    hostname: kafka_broker1
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker2
    hostname: kafka_broker2
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_broker3
    hostname: kafka_broker3
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka_rest1
    hostname: kafka_rest1
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    dockerfile: Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  # inventory:
  #   group_vars:
  #     all:
  #       zookeeper:
  #         properties:
  #           syncLimit: 3
  # playbooks:
  #   prepare: ../prepare.yml
  #   converge: ../converge.yml
verifier:
  name: ansible
