- name: Install Java
  package:
    name: "{{ openjdk_package }}"
    state: latest

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

# Import Distribution Specific tasks
- name: "Include os {{ ansible_os_family }} specific"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install the Confluent Platform
  package:
    name: "{{ package_name }}"
    state: "{% if confluent.latest %}latest{% else %}present{% endif %}"
  become: yes

- import_tasks: ssl_certs.yml
  when: security_mode == "ssl" or security_mode == "sasl_ssl"
