- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
  become: yes

- name: copy ssl related files to host
  synchronize:
    src: generated_ssl_files/
    dest: /var/ssl/private
  become: yes
