---
- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{ksql_listener_port}}/info"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not ksql_ssl_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: ksql_ssl_enabled|bool and not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC - HTTPS
  uri:
    url: "https://localhost:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: no
    url_username: "{{rbac_principal_name}}"
    url_password: "{{rbac_principal_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: ksql_ssl_enabled|bool and rbac_enabled|bool
