---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

# Install Packages
- name: Install the KSQL Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{ksql_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the KSQL Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{ksql_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Ksql Group
  group:
    name: "{{ksql.group}}"

- name: Create Ksql User
  user:
    name: "{{ksql.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ksql.group}}"

- name: Set Ksql streams dir permissions
  file:
    path: "{{ksql.properties['ksql.streams.state.dir']}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0755

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{ksql_truststore_storepass}}"
    truststore_path: "{{ksql_truststore_path}}"
    keystore_path: "{{ksql_keystore_path}}"
    keystore_storepass: "{{ksql_keystore_storepass}}"
    keystore_keypass: "{{ksql_keystore_keypass}}"
    service_name: ksql
    hostnames: "{{ [inventory_hostname] }}"
  when: ksql_ssl_enabled|bool or kafka_broker_listeners[ksql_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{ksql.group}}"
    kerberos_user: "{{ksql.user}}"
    kerberos_keytab_path: "{{ksql_kerberos_keytab_path}}"
    kerberos_handler: "restart ksql"
  when: kafka_broker_listeners[ksql_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Configure RBAC
  include_tasks: rbac.yml
  when: rbac_enabled|bool
  
## RBAC Configuration 

# - name: Create pem file Directory
#   file:
#     path: "{{rbac_enabled_public_pem_path}}"
#     group: "{{kafka_broker.group}}"
#     mode: '650'
#     recurse: yes
#   when: rbac_enabled|bool 

# - name: Copy in public pem files
#   copy:
#     src: "{{token_services_public_pem_file}}"
#     dest: "{{rbac_enabled_public_pem_path}}"
#     mode: '755'
#     owner: "{{kafka_broker.user}}"
#     group: "{{kafka_broker.group}}"
#   when: rbac_enabled|bool

# - name: export certificate to pem format for MDS login to create user
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   shell: |
#     openssl pkcs12 -in /var/ssl/private/kafka_broker.keystore.jks \
#       -out /var/ssl/private/kafka_broker.keystore.pem \
#       -passin pass:{{kafka_broker_keystore_storepass}} -passout pass:{{kafka_broker_keystore_storepass}} -clcerts
#   when: rbac_enabled|bool and ssl_enabled|bool

# - name: Get Kafka Cluster ID from Zookeeper
#   delegate_to: "{{ groups['zookeeper'][0] }}"
#   shell: |
#     /bin/zookeeper-shell localhost:2181 get /cluster/id 2> /dev/null | grep version | jq -r .id
#   register: cluster_id  
#   when: rbac_enabled|bool 

# - name: Login to MDS to get Security Token
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -u "{{mds_super_user}}":"{{mds_super_user_password}}" -s https://localhost:8090/security/1.0/authenticate 2> /dev/null | grep auth_token | jq -r .auth_token
#   register: rbac_token 
#   when: rbac_enabled|bool

# ## Configure users for RBAC with MTLS and self signed certificates

# - name: Grant SecurityAdmin role on KSQL user 
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/SecurityAdmin -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}","ksql-cluster":"default_"}}'
#   when: (rbac_enabled|bool and ssl_enabled|bool) and not (ssl_custom_certs|bool)

# - name: Grant Resource owner of KSQL Cluster on KSQL User
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/ResourceOwner/bindings -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}","ksql-cluster":"default_"}},"resourcePatterns":[{"resourceType": "KsqlCluster","name": "ksql-cluster"}]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
#   when: (rbac_enabled|bool and ssl_enabled|bool) and not (ssl_custom_certs|bool)

# - name: Grant ksql user the ResourceOwner role with three resourcePatterns
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/ResourceOwner/bindings -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_confluent-ksql-default__command_topic","patternType":"LITERAL"},{"resourceType":"Topic","name":"default_-ksql_processing_log","patternType":"LITERAL"},{"resourceType":"Group","name":"_confluent-ksql-default_","patternType":"PREFIXED"}]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
#   when: (rbac_enabled|bool and ssl_enabled|bool) and not (ssl_custom_certs|bool)

# ## Configure users for RBAC with MTLS and custom certificates

# - name: Grant SecurityAdmin role on KSQL user 
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_principal_name}}/roles/SecurityAdmin -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}","ksql-cluster":"default_"}}'
#   when: rbac_enabled|bool and ssl_enabled|bool and ssl_custom_certs|bool

# - name: Grant Resource owner of KSQL Cluster on KSQL User
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_principal_name}}/roles/ResourceOwner/bindings -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}","ksql-cluster":"default_"}},"resourcePatterns":[{"resourceType": "KsqlCluster","name": "ksql-cluster"}]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
#   when: rbac_enabled|bool and ssl_enabled|bool and ssl_custom_certs|bool

# - name: Grant ksql user the ResourceOwner role with three resourcePatterns
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_principal_name}}/roles/ResourceOwner/bindings -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_confluent-ksql-default__command_topic","patternType":"LITERAL"},{"resourceType":"Topic","name":"default_-ksql_processing_log","patternType":"LITERAL"},{"resourceType":"Group","name":"_confluent-ksql-default_","patternType":"PREFIXED"}]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
#   when: rbac_enabled|bool and ssl_enabled|bool and ssl_custom_certs|bool

# - name: Remove exported pem file for MDS login
#   file:
#      path: /var/ssl/private/kafka_broker.keystore.pem
#      state: absent
#   when: rbac_enabled|bool and ssl_enabled|bool 

- name: Change streams directory ownership
  file:
    path: "{{ksql_streams_state_dir}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0750

- name: Create Ksql Config
  template:
    src: ksql-server.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - restart ksql

- name: Create Logs Directory
  file:
    path: "{{ksql.appender_log_path}}"
    state: directory
    group: "{{ksql.group}}"
    owner: "{{ksql.user}}"
    mode: '764'

- name: Create Ksql log4j Config
  template:
    src: ksql-server_log4j.properties.j2
    dest: "{{ksql.log4j_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - restart ksql

- name: Ksql Jaas Config
  template:
    src: ksql-server_jaas.conf.j2
    dest: "{{ksql.jaas_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: kafka_broker_listeners[ksql_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'
  notify:
    - restart ksql

- name: Create Service Override Directory
  file:
    path: "{{ksql.systemd_override | dirname}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{ksql.systemd_override}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - reload systemd
    - restart ksql

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart ksql
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Ksql Service
  systemd:
    name: "{{ksql_service_name}}"
    enabled: yes
    state: started

- name: Health Check
  include_tasks: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
