---
- name: Get Principal used on the Inter Broker Listener
  include_tasks: set_principal.yml
  when: ksql_log_streaming_enabled | bool

- name: RBAC Setup Tasks
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    user: "{{ksql_user}}"
    group: "{{ksql_group}}"

- name: Grant role System Admin to Additional KSQL Super Users
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{item}}/roles/SystemAdmin"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "clusters": {
          "kafka-cluster": "{{kafka_cluster_id}}",
          "ksql-cluster": "{{ksql_final_properties['ksql.service.id']}}"
        }
      }
    status_code: 204
  loop: "{{ksql_additional_system_admins}}"
  when: not ansible_check_mode

- name: Grant ResourceOwner of KSQL Cluster on KSQL User
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "ksql-cluster":"{{ksql_final_properties['ksql.service.id']}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "KsqlCluster",
          "name": "ksql-cluster"
        }]
      }
    status_code: 204
  when: not ansible_check_mode

- name: Grant ksql user the ResourceOwner role with four resourcePatterns
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [
          {
            "resourceType":"Group",
            "name":"_confluent-ksql-{{ksql_final_properties['ksql.service.id']}}",
            "patternType":"PREFIXED"
          },
          {
            "resourceType":"Topic",
            "name": "_confluent-ksql-{{ksql_final_properties['ksql.service.id']}}",
            "patternType": "PREFIXED"
          }
        ]
      }
    status_code: 204
  when: not ansible_check_mode

- name: Grant ksql user the DeveloperWrite role on resourceType TransactionalId
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/DeveloperWrite/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "TransactionalId",
          "name": "{{ksql_final_properties['ksql.service.id']}}",
          "patternType":"LITERAL"
        }]
      }
    status_code: 204
  when: not ansible_check_mode

- name: Grant ksql user the ResourceOwner role on resourceType Subject in Schema Registry Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}",
            "schema-registry-cluster":"{{schema_registry_final_properties['schema.registry.group.id']}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "Subject",
          "name": "_confluent-ksql-{{ksql_final_properties['ksql.service.id']}}",
          "patternType":"PREFIXED"
        }]
      }
    status_code: 204
  when: ("'schema_registry' in groups") and not ansible_check_mode

- name: Grant ksql user the DeveloperWrite role on Monitoring Interceptor Topic
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/principals/User:{{ksql_ldap_user}}/roles/DeveloperWrite/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [{
          "resourceType": "Topic",
          "name": "{{ksql_final_properties['confluent.monitoring.interceptor.topic']}}",
          "patternType":"LITERAL"
        }]
      }
    status_code: 204
  when: ksql_monitoring_interceptors_enabled|bool and not ansible_check_mode

- name: Grant ksql user the ResourceOwner role on the Processing Log Topic
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/principals/User:{{item}}/roles/ResourceOwner/bindings"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "scope": {
          "clusters": {
            "kafka-cluster":"{{kafka_cluster_id}}"
          }
        },
        "resourcePatterns": [
          {
            "resourceType":"Topic",
            "name":"{{ksql_final_properties['ksql.logging.processing.topic.name']}}",
            "patternType":"LITERAL"
          }
        ]
      }
    status_code: 204
  loop:
    - "{{ksql_ldap_user}}"
    - "{{ksql_log4j_principal}}"
  when: ksql_log_streaming_enabled | bool and not ansible_check_mode
