---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
- kafka.connect:type=connect-worker-metrics
- kafka.connect:type=connect-metrics,client-id=*
- kafka.connect:type=connector-task-metrics,connector=*,task=*
rules:
- pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
  name: "kafka_connect_connect_worker_metrics_$1"
- pattern: "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
  name: "kafka_connect_connect_metrics_$1_$2"
- pattern: "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"
  name: "kafka_connect_connect_connector_metrics"
  value: 1
  labels:
    connector: $1
    task: $2
    status: $3
