---
- name: Wait for API to return 200
  uri:
    url: "{{kafka_rest_http_protocol}}://{{inventory_hostname}}:{{kafka_rest_port}}/topics"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC
  uri:
    url: "{{kafka_rest_http_protocol}}://{{inventory_hostname}}:{{kafka_rest_port}}/topics"
    status_code: 200
    validate_certs: false
    url_username: "{{kafka_rest_ldap_user}}"
    url_password: "{{kafka_rest_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: rbac_enabled|bool
