---
- name: Restart Kafka Rest
  systemd:
    daemon_reload: true
    name: "{{kafka_rest_service_name}}"
    state: restarted

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_rest_health_check_delay }}"
