---
- name: Restart kafka-rest Service
  systemd:
    daemon_reload: true
    name: "{{kafka_rest_service_name}}"
    state: restarted

- name: Health Check
  include: health_check.yml
  when:
    - kafka_rest_health_checks_enabled|bool
    - not ansible_check_mode
  tags: health_check
