---
- name: Verify
  hosts: zookeeper
  tasks:
    - name: Get Stats on override.conf
      stat:
        path: /etc/systemd/system/confluent-zookeeper.service.d/override.conf
      register: override_conf

    - name: Assert ownership on override.conf
      assert:
        that:
          - override_conf.stat.gr_name == "confluent"
          - override_conf.stat.pw_name == "cp-kafka"
        quiet: yes
