---
### Validates that Schema Registry SASL Plain configs are correct.
### Validates that Replication Factor is 3.
### Validates that all components connect to Confluent Cloud.

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: kafkastore.sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

    - name: Check Replication Factor set to 3 eventhough there is no kafka group in inventory
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: kafkastore.topic.replication.factor
        expected_value: "3"

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

    - name: Check Replication Factor set to 3 eventhough there is no kafka group in inventory
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: status.storage.replication.factor
        expected_value: "3"

    - name: Check SR url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: key.converter.schema.registry.url
        expected_value: https://ccloud-schema-registry1:8081

    - name: Check SR creds
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: value.converter.schema.registry.basic.auth.user.info
        expected_value: admin:admin-secret

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: client.sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

    - name: Check schema registry url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: schema.registry.url
        expected_value: https://ccloud-schema-registry1:8081

    - name: Check schema registry creds
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: schema.registry.basic.auth.user.info
        expected_value: admin:admin-secret

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - name: Check Replication Factor set to 3 eventhough there is no kafka group in inventory
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.internal.topic.replicas
        expected_value: "3"

    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

    - name: Check schema registry url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.schema.registry.url
        expected_value: https://ccloud-schema-registry1:8081

    - name: Check schema registry creds
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.schema.registry.basic.auth.user.info
        expected_value: admin:admin-secret

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - name: Check Replication Factor set to 3 eventhough there is no kafka group in inventory
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.command.topic.replication
        expected_value: "3"

    - name: Check Max Message Bytes Property
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.metrics.topic.max.message.bytes
        expected_value: "8388608"

    - name: Check jaas config properly set
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.monitoring.interceptor.sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="client" password="client-secret";'

    - name: Check schema registry url
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.schema.registry.url
        expected_value: https://ccloud-schema-registry1:8081

    - name: Check schema registry creds
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.schema.registry.basic.auth.user.info
        expected_value: admin:admin-secret
