---
- name: Delete SSL Certificate Generation Directory
  file:
    path: "{{ ssl_file_dir_final }}/generation"
    state: absent

- name: Delete Old Certificate Files
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{keystore_path}}"
    - "{{truststore_path}}"
    - "{{bcfks_keystore_path|default(keystore_path)}}"
    - "{{bcfks_truststore_path|default(truststore_path)}}"
    - "{{ca_cert_path}}"
    - "{{cert_path}}"
    - "{{key_path}}"
  when: not ( ssl_provided_keystore_and_truststore_remote_src|bool )

- name: Delete Old Certificate Files
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{ca_cert_path}}"
    - "{{cert_path}}"
    - "{{key_path}}"
  when: ( ssl_provided_keystore_and_truststore_remote_src|bool )

- name: Create SSL Certificate Generation Directory
  file:
    path: "{{ ssl_file_dir_final }}/generation"
    state: directory
    mode: 0755

- name: Create Keystore and Truststore with Self Signed Certs
  include_tasks: self_signed_certs.yml
  when: self_signed|bool

- name: Create Keystore and Truststore with Custom Certs
  include_tasks: custom_certs.yml
  when: ssl_custom_certs|bool

- name: Copy Provided Keystore and Truststore to Host
  include_tasks: provided_keystore_and_truststore.yml
  when: ssl_provided_keystore_and_truststore|bool

- name: Delete SSL Certificate Generation Directory and Files
  file:
    path: "{{ ssl_file_dir_final }}/{{item}}"
    state: absent
  loop:
    - generation
    - ca.srl
  when: delete_generation_dir|bool

- set_fact:
    certs_updated: true
