ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  streams_state_dir: /var/lib/kafka-streams
  environment:
    KSQL_HEAP_OPTS: "-Xmx3g"
  config:
    application.id: ksql-server
    listeners: http://localhost:8088
    ksql.streams.replication.factor: 3
    ksql.sink.replicas: 3
    ksql.streams.num.standby.replicas: 1
  systemd:
    enabled: yes
    state: started
