ksql_listener_port: 8088

ksql_open_file_limit: "{{open_file_limit}}"

ksql_jaas_file: /etc/ksql/ksql-server_jaas.conf
ksql_jaas_java_arg_buildout: "-Djava.security.auth.login.config={{ksql_jaas_file}}"
ksql_jaas_java_arg: "{{ ksql_jaas_java_arg_buildout if security_mode in ['kerberos', 'kerberos_ssl', 'kerberos_ssl_customcerts'] else '' }}"

ksql_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{ksql_jolokia_port}},host=0.0.0.0"
ksql_jolokia_java_arg: "{{ ksql_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

ksql_kafka_opts_buildout: "{{ ksql_jolokia_java_arg + ' ' + ksql_jaas_java_arg if ksql_jolokia_java_arg != '' or ksql_jaas_java_arg != '' else '' }}"

ksql_service_environment_overrides:
  KSQL_HEAP_OPTS: "-Xmx3g"
  KAFKA_OPTS: "{{ ksql_kafka_opts_buildout }}"
ksql_service_overrides:
  LimitNOFILE: "{{ksql_open_file_limit}}"

ksql_packages:
  - confluent-ksql
  - confluent-security

ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_file: /usr/lib/systemd/system/confluent-ksql.service
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  streamsDataDir: /var/lib/kafka-streams
  systemd:
    enabled: yes
    state: started
  properties:
    application.id: ksql-server
    listeners: http://0.0.0.0:{{ksql_listener_port}}
    ssl.endpoint.identification.algorithm: ""
    ksql.streams.state.dir: /var/lib/kafka-streams
