ksql_listener_port: 8088

ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  keytab: /etc/security/keytabs
  jaas_file: /etc/ksql/ksql-server_jaas.conf
  streamsDataDir: /var/lib/kafka-streams
  systemd:
    enabled: yes
    state: started
  environment:
    KSQL_HEAP_OPTS: "-Xmx3g"
  kerberosEnvironment:
    KSQL_HEAP_OPTS: "-Xmx3g"
    KSQL_OPTS: "-Djava.security.auth.login.config=/etc/ksql/ksql-server.jaas.conf"
  config:
    application.id: ksql-server
    listeners: http://0.0.0.0:{{ksql_listener_port}}
    ssl.endpoint.identification.algorithm: ""
    ksql.streams.state.dir=/var/lib/kafka-streams
