---
- name: Restart Kafka Connect Replicator Service
  systemd:
    daemon_reload: true
    name: "{{kafka_connect_replicator_service_name}}"
    state: restarted

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_connect_replicator_health_check_delay }}"
