---

all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: ~/ssh_pems/cp-ansible.pem
    validate_hosts: false
    ansible_python_interpreter: /usr/bin/python3
      # ssl_enabled: true
    mask_secrets: false
      # self_signed: true
      # redhat_java_package_name: java-11-openjdk
    debian_java_package_name: openjdk-17-jdk
    confluent_package_version: '7.7.0'
    confluent_full_package_version: '7.7.0~0-1'  
    confluent_common_repository_baseurl: https://jenkins-confluent-packages.s3.us-west-2.amazonaws.com/7.7.x/92
    confluent_package_debian_suffix: '=7.7.0~0-1'

    
zookeeper:
  hosts:
    ec2-34-221-106-93.us-west-2.compute.amazonaws.com:

kafka_broker:
  hosts:
    ec2-34-221-106-93.us-west-2.compute.amazonaws.com:

schema_registry:
  hosts:
    ec2-34-221-106-93.us-west-2.compute.amazonaws.com:

kafka_connect:
  hosts:
    ec2-52-35-241-118.us-west-2.compute.amazonaws.com:

kafka_rest:
  hosts:
    ec2-52-35-241-118.us-west-2.compute.amazonaws.com:

ksql:
  hosts:
    ec2-52-35-241-118.us-west-2.compute.amazonaws.com:

control_center:
  hosts:
    ec2-52-35-241-118.us-west-2.compute.amazonaws.com: