---
- name: Create Directory on Controller for Host Error Files
  file:
    state: directory
    path: "troubleshooting"
    mode: 0755
  delegate_to: localhost
  vars:
    ansible_connection: local
    ansible_become: "{{ ansible_become_localhost }}"

- name: Register all Log Files
  find:
    paths: "{{log_dir}}"
    recurse: false
  register: find_output

- name: Remove directory
  file:
    path: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}/"
    state: absent

- name: Recreate directory
  file:
    path: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}/"
    state: directory
    mode: 0750
    owner: "{{user}}"
    group: "{{group}}"

- name: Copy Config and Log Files to tmp dir
  copy:
    dest: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}/"
    src: "{{ item }}"
    remote_src: true
    mode: 0750
    owner: "{{user}}"
    group: "{{group}}"
  loop: "{{ find_output.files | map(attribute='path') | list + [config_file] }}"

- name: Archive log files
  archive:
    path: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}"
    dest: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}.tar.gz"
    remove: true
    format: gz
    force_archive: true
    mode: 0750
    owner: "{{user}}"
    group: "{{group}}"

- name: Fetch Config and Log Files
  fetch:
    src: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}.tar.gz"
    dest: "troubleshooting/"
    flat: true

- name: Clean temp directory
  file:
    path: "{{fetch_logs_path}}/troubleshooting/{{inventory_hostname}}/"
    state: absent

- name: Review logs message
  debug:
    msg: Review logs and property files in troubleshooting/ directory
