---
- name: Export CA Cert from Truststore
  shell: |
    keytool -exportcert -rfc \
      -alias "{{ssl_truststore_ca_cert_alias}}" \
      -storepass {{truststore_storepass}}  \
      -file {{ca_cert_path}} \
      -keystore {{truststore_path}}

- name: Export the Cert and Key from Keystore
  block:
    # Assuming the keystore is already in pkcs12 format
    - name: Export Certificate from Keystore
      shell: |
        openssl pkcs12 -in {{keystore_path}} \
          -nokeys -out {{cert_path}} \
          -passin pass:{{keystore_storepass}}

    - name: Export Key from Keystore
      shell: |
        openssl pkcs12 -in {{keystore_path}} \
          -nodes -nocerts -out {{key_path}} \
          -passin pass:{{keystore_storepass}}
  rescue:
    # Failed because the keystore in jks format
    - set_fact:
        extra_args: ""
      when: not fips_enabled|bool

    - set_fact:
        extra_args: "-providerpath {{fips_jar_path}} -providerclass {{fips_provider_class}}"
      when: fips_enabled|bool

    - name: Convert Keystore to Pem Format
      shell: |
        keytool -noprompt -importkeystore \
          -srckeystore {{keystore_path}} \
          -srcstorepass {{keystore_storepass}} \
          -destkeystore /var/ssl/private/generation/{{service_name}}.p12 \
          -deststoretype PKCS12 \
          -deststorepass {{keystore_storepass}} \
          -destkeypass {{keystore_storepass}} {{extra_args}}
      failed_when: false

    - name: Export Certificate
      shell: |
        openssl pkcs12 -in /var/ssl/private/generation/{{service_name}}.p12 \
          -nokeys -out {{cert_path}} \
          -passin pass:{{keystore_storepass}}

    - name: Export Key
      shell: |
        openssl pkcs12 -in /var/ssl/private/generation/{{service_name}}.p12 \
          -nodes -nocerts -out {{key_path}} \
          -passin pass:{{keystore_storepass}}

- name: Set certs already exported
  set_fact:
    certs_already_exported: true
