---
- name: Copy CA Cert to Host
  copy:
    src: "{{ssl_self_signed_ca_cert_filepath}}"
    dest: "{{ca_cert_path}}"

- name: Copy CA Key to Host
  copy:
    src: "{{ssl_self_signed_ca_key_filepath}}"
    dest: "{{ca_key_path}}"

- name: Create Host Key
  shell: |
    openssl genrsa -out {{key_path}} {{ssl_key_size}}

- name: Create Certificate Signing Request
  shell: |
    openssl req -new -key {{key_path}} \
      -out {{ ssl_file_directory }}generation/client.csr \
      -subj '/CN={{service_name}}/OU=TEST/O=CONFLUENT/L=PaloAlto/ST=Ca/C=US'

- name: Create Openssl Config for SAN
  template:
    src: openssl-san.cnf.j2
    dest: "{{ ssl_file_directory }}generation/openssl-san.cnf"

- name: Sign CSR with the Certificate Authority
  shell: |
    openssl x509 -req -CA {{ca_cert_path}} \
      -CAkey {{ca_key_path}} \
      -in {{ ssl_file_directory }}generation/client.csr \
      -out {{cert_path}} \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ssl_self_signed_ca_password}} \
      -extfile {{ ssl_file_directory }}generation/openssl-san.cnf \
      -extensions v3_req
  no_log: "{{mask_secrets|bool}}"

- name: Create Cert Chain
  shell: |
    cat {{ca_cert_path}} {{cert_path}} > {{ ssl_file_directory }}{{service_name}}.chain

- name: Create Keystore and Truststore from Certs
  include_tasks: create_keystores_from_certs.yml
