---
- name: Create CA
  shell: |
    openssl req -new -x509 \
      -keyout /var/ssl/private/generation/{{ssl_self_signed_ca_key_filename}} \
      -out /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -days 365 \
      -subj '/CN=ca1.test.confluent.io/OU=TEST/O=CONFLUENT/L=PaloAlto/S=Ca/C=US' \
      -passin pass:{{ssl_self_signed_ca_password}} -passout pass:{{ssl_self_signed_ca_password}}

- name: Create Truststore and Import the CA Cert (FIPS Enabled)
  shell: |
    keytool -noprompt -keystore {{truststore_path}} -storetype pkcs12 \
      -alias CARoot -import -file /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -storepass {{truststore_storepass}} -keypass {{truststore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Create Keystore (FIPS Enabled)
  shell: |
    keytool -genkey -noprompt \
      -storetype pkcs12 \
      -keyalg RSA -keysize 2048 \
      -alias {{inventory_hostname}} \
      -dname "CN={{inventory_hostname}},OU=TEST,O=CONFLUENT,L=PaloAlto,S=Ca,C=US" \
      -ext san=dns:{{inventory_hostname}} \
      -keystore {{keystore_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Create Certificate Signing Request (FIPS Enabled)
  shell: |
    keytool -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias {{inventory_hostname}} \
      -certreq -file /var/ssl/private/generation/client.csr \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Sign CSR with the Certificate Authority (FIPS Enabled)
  shell: |
    openssl x509 -req -CA /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -CAkey /var/ssl/private/generation/{{ssl_self_signed_ca_key_filename}} \
      -in /var/ssl/private/generation/client.csr \
      -out /var/ssl/private/generation/client-signed.crt \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ssl_self_signed_ca_password}}

- name: Import the CA cert into the Keystore (FIPS Enabled)
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}

- name: Import the Signed Host Cert into the Keystore (FIPS Enabled)
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias {{inventory_hostname}} \
      -import -file /var/ssl/private/generation/client-signed.crt \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}} \
      -providerpath {{fips_jar_path}} \
      -providerclass {{fips_provider_class}}
