---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Java Version
      shell: java -version
      register: version_output

    - name: Assert Java Version is 11
      assert:
        that:
          - version_output.stdout_lines[0].split(' ')[1] is version('11.0.0', '>=')
          - version_output.stdout_lines[0].split(' ')[1] is version('12.0.0', '<')
        fail_msg: "Current Java Version is: {{version_output.stdout_lines[0].split(' ')[1]}} Should be 11"
        quiet: true
