---
- name: Check file ownership
  stat:
    path: "{{custom_path}}{{file_name}}"
  register: path_exists

- name: Assert file exists
  assert:
    that:
      - path_exists.stat.exists
      - path_exists.stat.gr_name == '{{group}}'
      - path_exists.stat.pw_name == '{{user}}'
    fail_msg: "Log File: {{file_name}} does not exist."
    quiet: true
