---
- name: Wait for API to return 200
  uri:
    url: "{{schema_registry_http_protocol}}://localhost:{{schema_registry_listener_port}}/subjects"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not rbac_enabled|bool

- name: Wait for API to return 200 - RBAC
  uri:
    url: "{{schema_registry_http_protocol}}://localhost:{{schema_registry_listener_port}}/subjects"
    status_code: 200
    validate_certs: no
    url_username: "{{schema_registry_ldap_user}}"
    url_password: "{{schema_registry_ldap_password}}"
    force_basic_auth: true
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: rbac_enabled|bool
