---
- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{schema_registry_listener_port}}/config"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not schema_registry_ssl_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{schema_registry_listener_port}}/config"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: schema_registry_ssl_enabled|bool
