---
- name: Add Confluent Apt Key
  apt_key:
    url: "{{confluent_common.repository.debian.key_url}}"
    state: present
  when: not custom_apt_repo|bool

- name: Add Confluent Apt Repo
  apt_repository:
    repo: "{{confluent_common.repository.debian.repository}}"
    state: present
  when: not custom_apt_repo|bool

- name: Add Custom Apt Repo
  copy:
    src: "{{custom_apt_sourcelist_filepath}}"
    dest: /etc/apt/sources.list.d/custom_confluent.list
  when: custom_apt_repo|bool
  notify:
    - apt-get update

- meta: flush_handlers

# - fail: msg=whatever

  # echo "deb [trusted=yes] http://node4.example.com:8080 ./" > /etc/apt/sources.list.d/custom_confluent.list


- import_tasks: ubuntu_jvm.yml
  when:
    - ansible_distribution == "Ubuntu"
    - install_java|bool

- import_tasks: debian_jvm.yml
  when: ansible_distribution == "Debian"
