- name: Add Confluent apt key
  apt_key:
    url: "{{confluent_common.repository.debian.key_url}}"
    state: present
- name: Add Confluent apt repo
  apt_repository:
    repo: "{{confluent_common.repository.debian.repository}}"
    state: present
