---
- name: Confirm Hash Merging Enabled
  assert:
    that: lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'
    fail_msg: "Hash Merging must be enabled in ansible.cfg: Confirm current directory is cp-ansible and permissions are set to 755 not 777"
    quiet: true

- name: Gather OS Facts
  setup:
    # Only gathers items in list, filters out the rest
    filter: "{{item}}"
    gather_subset:
      - '!all'
  loop:
    - ansible_os_family
    - ansible_distribution

# JVM Installation and Repo Setup
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

# Process Archive File deployments
- name: Test for local Confluent Platform tarball already expanded into target
  stat:
    path: "{{archive_destination_path}}/confluent-{{confluent_archive_version}}"
  register: local_confluent_target

- name: Create Confluent Platform install directory
  file:
    path: "{{archive_destination_path}}"
    state: directory
    mode: 0755
  when: archive_file_enabled|bool

# This is needed to tell the future copy task to run or not because it will fail if this file doesn't exist
- name: Test for local Confluent Platform archive
  stat:
    path: "{{ confluent_archive_file_path }}"
  register: local_confluent_archive

- name: Create a temp directory to stage the Confluent Platform archive
  tempfile:
    state: directory
    suffix: staging
  register: archive_staging_tmp
  when: archive_file_enabled|bool

- name: Copy local Confluent Platform archive to a temporary directory
  copy:
    src: "{{ confluent_archive_file_path }}"
    remote_src: yes
    dest: "{{archive_staging_tmp.path}}"
  when:
    - archive_file_enabled|bool
    - local_confluent_archive.stat.exists|bool
    - local_confluent_target.stat.exists == false

# If the file exists in the staging/tmp directory then it won't be downloaded
- name: Download Confluent Platform archive
  get_url:
    url: "{{ confluent_common_repository_archive_url }}"
    dest: "{{archive_staging_tmp.path}}/{{confluent_archive_file_name}}"
    force: no
  when:
    - archive_file_enabled|bool
    - local_confluent_target.stat.exists == false

# Test for the target directory (i.e. creates) already existing. If so then skip expanding
- name: Expand Confluent Platform archive
  unarchive:
    src: "{{archive_staging_tmp.path}}/{{confluent_archive_file_name}}"
    remote_src: yes
    dest: "{{archive_destination_path}}"
    mode: 0755
    creates: "{{archive_destination_path}}/confluent-{{confluent_archive_version}}"
  when: archive_file_enabled|bool

- name: Create Jolokia directory
  file:
    path: /opt/jolokia
    state: directory
    mode: 0755
  when: jolokia_enabled|bool

- name: Download Jolokia Jar
  get_url:
    url: "{{ jolokia_jar_url }}"
    dest: "{{ jolokia_jar_path }}"
    mode: 0755
  register: joklokia_download_result
  until: joklokia_download_result is success
  retries: 5
  delay: 5
  when:
    - jolokia_enabled|bool
    - not ansible_check_mode

- name: Create Prometheus install directory
  file:
    path: /opt/prometheus
    state: directory
    mode: 0755
  when: jmxexporter_enabled|bool

- name: Download Prometheus JMX Exporter Jar
  get_url:
    url: "{{ jmxexporter_jar_url }}"
    dest: "{{ jmxexporter_jar_path }}"
    mode: 0755
  register: prometheus_download_result
  until: prometheus_download_result is success
  retries: 5
  delay: 5
  when:
    - jmxexporter_enabled|bool
    - not ansible_check_mode

- name: Download Confluent CLI - Standard
  shell: "curl -L https://cnfl.io/cli | sh -s -- -b {{ confluent_cli_path | dirname }}"
  args:
    creates: "{{ confluent_cli_path }}"
  register: cli_download_result
  until: cli_download_result is success
  retries: 5
  delay: 5
  when:
    - confluent_cli_download_enabled|bool
    - confluent_cli_custom_download_url is not defined

- name: Download Confluent CLI - Custom URL
  get_url:
    url: "{{ confluent_cli_custom_download_url }}"
    dest: "{{ confluent_cli_path }}"
    mode: 0755
  register: cli_download_result
  until: cli_download_result is success
  retries: 5
  delay: 5
  when:
    - confluent_cli_download_enabled|bool
    - confluent_cli_custom_download_url is defined

- set_fact:
    common_role_completed: true
