---
- name: Confirm Hash Merging Enabled
  assert:
    that: lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'
    fail_msg: "Hash Merging must be enabled in ansible.cfg: Confirm current directory is cp-ansible and permissions are set to 755 not 777"
    quiet: true

# JVM Installation and Repo Setup
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

- name: Create Jolokia directory
  file:
    path: /opt/jolokia
    state: directory
    mode: 0755
  when: jolokia_enabled|bool

- name: Download Jolokia Jar
  get_url:
    url: "{{ jolokia_jar_url }}"
    dest: "{{ jolokia_jar_path }}"
    mode: 0755
  when:
    - jolokia_enabled|bool
    - not ansible_check_mode

- name: Create Prometheus install directory
  file:
    path: /opt/prometheus
    state: directory
    mode: 0755
  when: jmxexporter_enabled|bool

- name: Download Prometheus JMX Exporter Jar
  get_url:
    url: "{{ jmxexporter_jar_url }}"
    dest: "{{ jmxexporter_jar_path }}"
    mode: 0755
  when:
    - jmxexporter_enabled|bool
    - not ansible_check_mode

- name: Download Confluent CLI - Standard
  shell: "curl -L https://cnfl.io/cli | sh -s -- -b {{ confluent_cli_path | dirname }}"
  args:
    creates: "{{ confluent_cli_path }}"
  retries: 5
  when:
    - confluent_cli_download_enabled|bool
    - confluent_cli_custom_download_url is not defined

- name: Download Confluent CLI - Custom URL
  get_url:
    url: "{{ confluent_cli_custom_download_url }}"
    dest: "{{ confluent_cli_path }}"
    mode: 0755
  when:
    - confluent_cli_download_enabled|bool
    - confluent_cli_custom_download_url is defined

- set_fact:
    common_role_completed: true
