---
- name: Add open JDK repo
  apt_repository:
    repo: "{{ubuntu_java_repository}}"
  when: not custom_apt_repo|bool

- name: Install Java
  apt:
    name: "{{ubuntu_java_package_name}}"
    # update_cache: yes
