---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.variables

    - name: Get stats on copied file
      stat:
        path: "/opt/confluent/confluent-{{confluent_package_version}}"
      register: archive

    - name: Assert copied file's permissions correct
      assert:
        that:
          - archive.stat.exists
          - archive.stat.gr_name == 'custom'
          - archive.stat.pw_name == 'cp-custom'
        quiet: true

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka/server.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka/server.properties
        property: zookeeper.ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/kafka-broker-security.properties:server.properties/zookeeper.ssl.truststore.password}

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/schema-registry/schema-registry.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/schema-registry/schema-registry.properties
        property: ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/schema-registry-security.properties:schema-registry.properties/ssl.truststore.password}

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka-rest/kafka-rest.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka-rest/kafka-rest.properties
        property: ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/kafka-rest-security.properties:kafka-rest.properties/ssl.truststore.password}

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka/connect-distributed.properties
        property: plugin.path
        expected_value: /opt/confluent/confluent-6.0.8/share/java,/usr/share/java

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka/connect-distributed.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/kafka/connect-distributed.properties
        property: ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/kafka-connect-security.properties:connect-distributed.properties/ssl.truststore.password}

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/ksqldb/ksql-server.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/ksqldb/ksql-server.properties
        property: ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/ksql-security.properties:ksql-server.properties/ssl.truststore.password}

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/confluent-control-center/control-center-production.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /opt/confluent/etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.streams.ssl.truststore.password
        expected_value: ${securepass:/var/ssl/private/control-center-security.properties:control-center-production.properties/confluent.controlcenter.streams.ssl.truststore.password}
