---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.variables

    - name: Download Tar
      get_url:
        url: "{{confluent_community_archive_url}}"
        dest: "{{ confluent_archive_file_source }}"

    - name: Download CLI tar
      get_url:
        url: "{{confluent_cli_archive_url}}"
        dest: "{{ confluent_cli_archive_file_source }}"
