---
### Validates that Confluent CLI is installed.
- name: Verify - Confluent CLI
  hosts: all
  gather_facts: false
  tasks:
    - name: Check confluent cli is installed
      command: "/usr/local/bin/confluent version"
