---
- name: Restart Zookeeper
  systemd:
    daemon_reload: true
    name: "{{zookeeper_service_name}}"
    state: restarted

- name: Startup Delay
  wait_for:
    timeout: "{{ zookeeper_health_check_delay }}"
